<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Introduction to Data Analysis with R &amp; Reproducible Data Science</title>
  <meta name="description" content="Introduction to Data Analysis with R &amp; Reproducible Data Science">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Introduction to Data Analysis with R &amp; Reproducible Data Science" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="IRSAAtUMn/RWorkshop18/docs" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction to Data Analysis with R &amp; Reproducible Data Science" />
  
  
  

<meta name="author" content="Institute for Research in Statistics and its Applications at the University of Minnesota">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="simple-statistics-in-r.html">
<link rel="next" href="logistic-regression-in-r.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.2/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.4/datatables.js"></script>
<link href="libs/dt-core-1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.16/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.16/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Home</a></li>
<li class="chapter" data-level="1" data-path="introduction-to-r-rstudio.html"><a href="introduction-to-r-rstudio.html"><i class="fa fa-check"></i><b>1</b> Introduction to R &amp; RStudio</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-r-rstudio.html"><a href="introduction-to-r-rstudio.html#getting-started"><i class="fa fa-check"></i><b>1.1</b> Getting Started</a></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-r-rstudio.html"><a href="introduction-to-r-rstudio.html#basic-features"><i class="fa fa-check"></i><b>1.2</b> Basic features</a></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-r-rstudio.html"><a href="introduction-to-r-rstudio.html#getting-help"><i class="fa fa-check"></i><b>1.3</b> Getting Help</a></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-r-rstudio.html"><a href="introduction-to-r-rstudio.html#working-with-data"><i class="fa fa-check"></i><b>1.4</b> Working with data</a></li>
<li class="chapter" data-level="1.5" data-path="introduction-to-r-rstudio.html"><a href="introduction-to-r-rstudio.html#exercises"><i class="fa fa-check"></i><b>1.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>2</b> Data Visualization</a><ul>
<li class="chapter" data-level="2.1" data-path="data-visualization.html"><a href="data-visualization.html#ggplot"><i class="fa fa-check"></i><b>2.1</b> ggplot</a></li>
<li class="chapter" data-level="2.2" data-path="data-visualization.html"><a href="data-visualization.html#univariate-visualizations"><i class="fa fa-check"></i><b>2.2</b> Univariate visualizations</a></li>
<li class="chapter" data-level="2.3" data-path="data-visualization.html"><a href="data-visualization.html#visualizing-relationships"><i class="fa fa-check"></i><b>2.3</b> Visualizing Relationships</a></li>
<li class="chapter" data-level="2.4" data-path="data-visualization.html"><a href="data-visualization.html#exercises-1"><i class="fa fa-check"></i><b>2.4</b> Exercises</a></li>
<li class="chapter" data-level="2.5" data-path="data-visualization.html"><a href="data-visualization.html#extra"><i class="fa fa-check"></i><b>2.5</b> Extra</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html"><i class="fa fa-check"></i><b>3</b> Simple Statistics in R</a><ul>
<li class="chapter" data-level="3.1" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#chapter-outline-and-goals"><i class="fa fa-check"></i><b>3.1</b> Chapter Outline and Goals</a></li>
<li class="chapter" data-level="3.2" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#minnesota-beer-data"><i class="fa fa-check"></i><b>3.2</b> Minnesota Beer Data</a><ul>
<li class="chapter" data-level="3.2.1" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#overview"><i class="fa fa-check"></i><b>3.2.1</b> Overview</a></li>
<li class="chapter" data-level="3.2.2" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#load-the-data"><i class="fa fa-check"></i><b>3.2.2</b> Load the Data</a></li>
<li class="chapter" data-level="3.2.3" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#look-at-the-data"><i class="fa fa-check"></i><b>3.2.3</b> Look at the Data</a></li>
<li class="chapter" data-level="3.2.4" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#plot-the-data"><i class="fa fa-check"></i><b>3.2.4</b> Plot the Data</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#descriptive-statistics-in-r"><i class="fa fa-check"></i><b>3.3</b> Descriptive Statistics in R</a><ul>
<li class="chapter" data-level="3.3.1" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#overview-1"><i class="fa fa-check"></i><b>3.3.1</b> Overview</a></li>
<li class="chapter" data-level="3.3.2" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#minimum-and-maximum"><i class="fa fa-check"></i><b>3.3.2</b> Minimum and Maximum</a></li>
<li class="chapter" data-level="3.3.3" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#mean-standard-deviation-and-variance"><i class="fa fa-check"></i><b>3.3.3</b> Mean, Standard Deviation, and Variance</a></li>
<li class="chapter" data-level="3.3.4" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#medians-and-quantiles"><i class="fa fa-check"></i><b>3.3.4</b> Medians and Quantiles</a></li>
<li class="chapter" data-level="3.3.5" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#factor-level-information"><i class="fa fa-check"></i><b>3.3.5</b> Factor Level Information</a></li>
<li class="chapter" data-level="3.3.6" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#covariances-and-correlations"><i class="fa fa-check"></i><b>3.3.6</b> Covariances and Correlations</a></li>
<li class="chapter" data-level="3.3.7" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#applying-functions-to-multiple-variables"><i class="fa fa-check"></i><b>3.3.7</b> Applying Functions to Multiple Variables</a></li>
<li class="chapter" data-level="3.3.8" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#applying-functions-at-levels-of-factors"><i class="fa fa-check"></i><b>3.3.8</b> Applying Functions at Levels of Factors</a></li>
<li class="chapter" data-level="3.3.9" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#making-a-table"><i class="fa fa-check"></i><b>3.3.9</b> Making a Table</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#students-t-test-in-r"><i class="fa fa-check"></i><b>3.4</b> Student’s t-Test in R</a><ul>
<li class="chapter" data-level="3.4.1" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#one-sample-t-test"><i class="fa fa-check"></i><b>3.4.1</b> One Sample t-Test</a></li>
<li class="chapter" data-level="3.4.2" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#two-sample-t-test"><i class="fa fa-check"></i><b>3.4.2</b> Two Sample t-Test</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#one-way-anova-in-r"><i class="fa fa-check"></i><b>3.5</b> One-Way ANOVA in R</a><ul>
<li class="chapter" data-level="3.5.1" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#omnibus-f-test"><i class="fa fa-check"></i><b>3.5.1</b> Omnibus F-Test</a></li>
<li class="chapter" data-level="3.5.2" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#pairwise-comparisons-tukeys-hsd"><i class="fa fa-check"></i><b>3.5.2</b> Pairwise Comparisons (Tukey’s HSD)</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#correlation-tests-in-r"><i class="fa fa-check"></i><b>3.6</b> Correlation Tests in R</a></li>
<li class="chapter" data-level="3.7" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#exercises-2"><i class="fa fa-check"></i><b>3.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html"><i class="fa fa-check"></i><b>4</b> Linear Regression in R</a><ul>
<li class="chapter" data-level="4.1" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#chapter-outline-and-goals-1"><i class="fa fa-check"></i><b>4.1</b> Chapter Outline and Goals</a></li>
<li class="chapter" data-level="4.2" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#minnesota-beer-data-reminder"><i class="fa fa-check"></i><b>4.2</b> Minnesota Beer Data (Reminder)</a><ul>
<li class="chapter" data-level="4.2.1" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#overview-2"><i class="fa fa-check"></i><b>4.2.1</b> Overview</a></li>
<li class="chapter" data-level="4.2.2" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#load-and-look-at-the-data"><i class="fa fa-check"></i><b>4.2.2</b> Load and Look at the Data</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#simple-linear-regression"><i class="fa fa-check"></i><b>4.3</b> Simple Linear Regression</a><ul>
<li class="chapter" data-level="4.3.1" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#fit-the-model"><i class="fa fa-check"></i><b>4.3.1</b> Fit the Model</a></li>
<li class="chapter" data-level="4.3.2" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#inference-information"><i class="fa fa-check"></i><b>4.3.2</b> Inference Information</a></li>
<li class="chapter" data-level="4.3.3" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#plot-the-regression-line"><i class="fa fa-check"></i><b>4.3.3</b> Plot the Regression Line</a></li>
<li class="chapter" data-level="4.3.4" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#diagnostic-and-influence-plots"><i class="fa fa-check"></i><b>4.3.4</b> Diagnostic and Influence Plots</a></li>
<li class="chapter" data-level="4.3.5" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#prediction-for-new-data"><i class="fa fa-check"></i><b>4.3.5</b> Prediction for New Data</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#multiple-linear-regression"><i class="fa fa-check"></i><b>4.4</b> Multiple Linear Regression</a><ul>
<li class="chapter" data-level="4.4.1" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#overview-3"><i class="fa fa-check"></i><b>4.4.1</b> Overview</a></li>
<li class="chapter" data-level="4.4.2" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#additive-effects"><i class="fa fa-check"></i><b>4.4.2</b> Additive Effects</a></li>
<li class="chapter" data-level="4.4.3" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#interaction-effects"><i class="fa fa-check"></i><b>4.4.3</b> Interaction Effects</a></li>
<li class="chapter" data-level="4.4.4" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#comparing-fit-models"><i class="fa fa-check"></i><b>4.4.4</b> Comparing Fit Models</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#exercises-3"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html"><i class="fa fa-check"></i><b>5</b> Logistic Regression in R</a><ul>
<li class="chapter" data-level="5.1" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#introduction"><i class="fa fa-check"></i><b>5.1</b> Introduction</a><ul>
<li class="chapter" data-level="5.1.1" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#goals"><i class="fa fa-check"></i><b>5.1.1</b> Goals</a></li>
<li class="chapter" data-level="5.1.2" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#horseshoe-crab-data"><i class="fa fa-check"></i><b>5.1.2</b> Horseshoe Crab Data</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#model-basics"><i class="fa fa-check"></i><b>5.2</b> Model Basics</a><ul>
<li class="chapter" data-level="5.2.1" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#notation-and-setup"><i class="fa fa-check"></i><b>5.2.1</b> Notation and Setup</a></li>
<li class="chapter" data-level="5.2.2" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#fit-a-logistic-regression-model"><i class="fa fa-check"></i><b>5.2.2</b> Fit a Logistic Regression Model</a></li>
<li class="chapter" data-level="5.2.3" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#interpret-the-model"><i class="fa fa-check"></i><b>5.2.3</b> Interpret the Model</a></li>
<li class="chapter" data-level="5.2.4" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#calculate-probabilities"><i class="fa fa-check"></i><b>5.2.4</b> Calculate Probabilities</a></li>
<li class="chapter" data-level="5.2.5" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#test-a-regression-coefficient"><i class="fa fa-check"></i><b>5.2.5</b> Test a Regression Coefficient</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#half-time-exercises"><i class="fa fa-check"></i><b>5.3</b> Half-Time Exercises</a><ul>
<li class="chapter" data-level="5.3.1" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#female-horseshoe-crab-weight"><i class="fa fa-check"></i><b>5.3.1</b> Female Horseshoe Crab Weight</a></li>
<li class="chapter" data-level="5.3.2" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#boundary-water-blowdown"><i class="fa fa-check"></i><b>5.3.2</b> Boundary Water Blowdown</a></li>
<li class="chapter" data-level="5.3.3" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#beer"><i class="fa fa-check"></i><b>5.3.3</b> Beer</a></li>
<li class="chapter" data-level="5.3.4" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#state-colors"><i class="fa fa-check"></i><b>5.3.4</b> State Colors</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#beyond-the-basics"><i class="fa fa-check"></i><b>5.4</b> Beyond the Basics</a><ul>
<li class="chapter" data-level="5.4.1" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#interpret-the-model-again"><i class="fa fa-check"></i><b>5.4.1</b> Interpret the Model (Again!)</a></li>
<li class="chapter" data-level="5.4.2" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#incorporate-a-categorical-predictor"><i class="fa fa-check"></i><b>5.4.2</b> Incorporate a Categorical Predictor</a></li>
<li class="chapter" data-level="5.4.3" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#incorporate-multiple-predictors"><i class="fa fa-check"></i><b>5.4.3</b> Incorporate Multiple Predictors</a></li>
<li class="chapter" data-level="5.4.4" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#test-a-regression-coefficient-again"><i class="fa fa-check"></i><b>5.4.4</b> Test a Regression Coefficient (Again!)</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#more-exercises"><i class="fa fa-check"></i><b>5.5</b> More Exercises</a><ul>
<li class="chapter" data-level="5.5.1" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#crabs-revisited"><i class="fa fa-check"></i><b>5.5.1</b> Crabs, Revisited</a></li>
<li class="chapter" data-level="5.5.2" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#beer-revisited"><i class="fa fa-check"></i><b>5.5.2</b> Beer, Revisited</a></li>
<li class="chapter" data-level="5.5.3" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#state-colors-revisited"><i class="fa fa-check"></i><b>5.5.3</b> State Colors, Revisited</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#partial-solutions"><i class="fa fa-check"></i><b>5.6</b> Partial Solutions</a><ul>
<li class="chapter" data-level="5.6.1" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#crab-weight"><i class="fa fa-check"></i><b>5.6.1</b> Crab Weight</a></li>
<li class="chapter" data-level="5.6.2" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#boundary-water-blowdown-1"><i class="fa fa-check"></i><b>5.6.2</b> Boundary Water Blowdown</a></li>
<li class="chapter" data-level="5.6.3" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#beer-1"><i class="fa fa-check"></i><b>5.6.3</b> Beer</a></li>
<li class="chapter" data-level="5.6.4" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#state-colors-1"><i class="fa fa-check"></i><b>5.6.4</b> State Colors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html"><i class="fa fa-check"></i><b>6</b> Using R Reproducibly</a><ul>
<li class="chapter" data-level="6.1" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#types-of-reproducibility"><i class="fa fa-check"></i><b>6.1</b> Types of Reproducibility</a></li>
<li class="chapter" data-level="6.2" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#general-principles-of-reproducibility"><i class="fa fa-check"></i><b>6.2</b> General Principles of Reproducibility</a><ul>
<li class="chapter" data-level="6.2.1" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#dont-do-things-by-hand"><i class="fa fa-check"></i><b>6.2.1</b> Don’t do things by hand</a></li>
<li class="chapter" data-level="6.2.2" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#automate-where-you-can"><i class="fa fa-check"></i><b>6.2.2</b> Automate where you can</a></li>
<li class="chapter" data-level="6.2.3" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#use-version-control"><i class="fa fa-check"></i><b>6.2.3</b> Use Version Control</a></li>
<li class="chapter" data-level="6.2.4" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#document-your-environment"><i class="fa fa-check"></i><b>6.2.4</b> Document your environment</a></li>
<li class="chapter" data-level="6.2.5" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#document-your-analysis"><i class="fa fa-check"></i><b>6.2.5</b> Document your analysis</a></li>
<li class="chapter" data-level="6.2.6" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#make-your-data-open"><i class="fa fa-check"></i><b>6.2.6</b> Make your data open</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#starting-a-reproducible-workflow-in-r"><i class="fa fa-check"></i><b>6.3</b> Starting a Reproducible Workflow in R</a><ul>
<li class="chapter" data-level="6.3.1" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#organization"><i class="fa fa-check"></i><b>6.3.1</b> Organization</a></li>
<li class="chapter" data-level="6.3.2" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#anatomy-of-a-script"><i class="fa fa-check"></i><b>6.3.2</b> Anatomy of a script</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html"><i class="fa fa-check"></i><b>7</b> An R Markdown Demo</a><ul>
<li class="chapter" data-level="7.1" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#license"><i class="fa fa-check"></i><b>7.1</b> License</a></li>
<li class="chapter" data-level="7.2" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#r"><i class="fa fa-check"></i><b>7.2</b> R</a></li>
<li class="chapter" data-level="7.3" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#rendering"><i class="fa fa-check"></i><b>7.3</b> Rendering</a></li>
<li class="chapter" data-level="7.4" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#markdown"><i class="fa fa-check"></i><b>7.4</b> Markdown</a></li>
<li class="chapter" data-level="7.5" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#r-markdown"><i class="fa fa-check"></i><b>7.5</b> R Markdown</a><ul>
<li class="chapter" data-level="7.5.1" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#look"><i class="fa fa-check"></i><b>7.5.1</b> Look</a></li>
<li class="chapter" data-level="7.5.2" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#rdo"><i class="fa fa-check"></i><b>7.5.2</b> What Does It Do?</a></li>
<li class="chapter" data-level="7.5.3" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#why-do-we-want-it"><i class="fa fa-check"></i><b>7.5.3</b> Why Do We Want It?</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#examples-not-involving-r"><i class="fa fa-check"></i><b>7.6</b> Examples Not Involving R</a><ul>
<li class="chapter" data-level="7.6.1" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#title-author-date"><i class="fa fa-check"></i><b>7.6.1</b> Title, Author, Date</a></li>
<li class="chapter" data-level="7.6.2" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#headers"><i class="fa fa-check"></i><b>7.6.2</b> Headers</a></li>
<li class="chapter" data-level="7.6.3" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#paragraphs"><i class="fa fa-check"></i><b>7.6.3</b> Paragraphs</a></li>
<li class="chapter" data-level="7.6.4" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#fonts"><i class="fa fa-check"></i><b>7.6.4</b> Fonts</a></li>
<li class="chapter" data-level="7.6.5" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#lists"><i class="fa fa-check"></i><b>7.6.5</b> Lists</a></li>
<li class="chapter" data-level="7.6.6" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#html-links"><i class="fa fa-check"></i><b>7.6.6</b> HTML Links</a></li>
<li class="chapter" data-level="7.6.7" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#tables"><i class="fa fa-check"></i><b>7.6.7</b> Tables</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#examples-involving-r"><i class="fa fa-check"></i><b>7.7</b> Examples Involving R</a><ul>
<li class="chapter" data-level="7.7.1" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#code-chunks"><i class="fa fa-check"></i><b>7.7.1</b> Code Chunks</a></li>
<li class="chapter" data-level="7.7.2" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#code-chunks-with-options"><i class="fa fa-check"></i><b>7.7.2</b> Code Chunks With Options</a></li>
<li class="chapter" data-level="7.7.3" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#plots"><i class="fa fa-check"></i><b>7.7.3</b> Plots</a></li>
<li class="chapter" data-level="7.7.4" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#r-in-text"><i class="fa fa-check"></i><b>7.7.4</b> R in Text</a></li>
<li class="chapter" data-level="7.7.5" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#rtables"><i class="fa fa-check"></i><b>7.7.5</b> Tables</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#latex-math"><i class="fa fa-check"></i><b>7.8</b> LaTeX Math</a></li>
<li class="chapter" data-level="7.9" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#caching-computation"><i class="fa fa-check"></i><b>7.9</b> Caching Computation</a></li>
<li class="chapter" data-level="7.10" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#summary"><i class="fa fa-check"></i><b>7.10</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="git-version-control.html"><a href="git-version-control.html"><i class="fa fa-check"></i><b>8</b> Git (Version Control)</a><ul>
<li class="chapter" data-level="8.1" data-path="git-version-control.html"><a href="git-version-control.html#license-1"><i class="fa fa-check"></i><b>8.1</b> License</a></li>
<li class="chapter" data-level="8.2" data-path="git-version-control.html"><a href="git-version-control.html#r-1"><i class="fa fa-check"></i><b>8.2</b> R</a></li>
<li class="chapter" data-level="8.3" data-path="git-version-control.html"><a href="git-version-control.html#version-control"><i class="fa fa-check"></i><b>8.3</b> Version Control</a><ul>
<li class="chapter" data-level="8.3.1" data-path="git-version-control.html"><a href="git-version-control.html#what-is-it"><i class="fa fa-check"></i><b>8.3.1</b> What is It?</a></li>
<li class="chapter" data-level="8.3.2" data-path="git-version-control.html"><a href="git-version-control.html#very-old-fashioned-version-control"><i class="fa fa-check"></i><b>8.3.2</b> Very Old Fashioned Version Control</a></li>
<li class="chapter" data-level="8.3.3" data-path="git-version-control.html"><a href="git-version-control.html#a-plethora-of-version-control-systems"><i class="fa fa-check"></i><b>8.3.3</b> A Plethora of Version Control Systems</a></li>
<li class="chapter" data-level="8.3.4" data-path="git-version-control.html"><a href="git-version-control.html#why"><i class="fa fa-check"></i><b>8.3.4</b> Why?</a></li>
<li class="chapter" data-level="8.3.5" data-path="git-version-control.html"><a href="git-version-control.html#mindshare"><i class="fa fa-check"></i><b>8.3.5</b> Mindshare</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="git-version-control.html"><a href="git-version-control.html#git"><i class="fa fa-check"></i><b>8.4</b> Git</a><ul>
<li class="chapter" data-level="8.4.1" data-path="git-version-control.html"><a href="git-version-control.html#git-versus-github"><i class="fa fa-check"></i><b>8.4.1</b> Git versus GitHub</a></li>
<li class="chapter" data-level="8.4.2" data-path="git-version-control.html"><a href="git-version-control.html#git-and-github-and-rstudio"><i class="fa fa-check"></i><b>8.4.2</b> Git and GitHub and RStudio</a></li>
<li class="chapter" data-level="8.4.3" data-path="git-version-control.html"><a href="git-version-control.html#getting-git"><i class="fa fa-check"></i><b>8.4.3</b> Getting Git</a></li>
<li class="chapter" data-level="8.4.4" data-path="git-version-control.html"><a href="git-version-control.html#what"><i class="fa fa-check"></i><b>8.4.4</b> What?</a></li>
<li class="chapter" data-level="8.4.5" data-path="git-version-control.html"><a href="git-version-control.html#using-git"><i class="fa fa-check"></i><b>8.4.5</b> Using Git</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="git-version-control.html"><a href="git-version-control.html#tell-git-who-you-are"><i class="fa fa-check"></i><b>8.5</b> Tell Git Who You Are</a></li>
<li class="chapter" data-level="8.6" data-path="git-version-control.html"><a href="git-version-control.html#starting-a-new-project-locally"><i class="fa fa-check"></i><b>8.6</b> Starting a New Project Locally</a></li>
<li class="chapter" data-level="8.7" data-path="git-version-control.html"><a href="git-version-control.html#starting-an-r-project-that-will-be-a-cran-package"><i class="fa fa-check"></i><b>8.7</b> Starting an R Project that will be a CRAN Package</a></li>
<li class="chapter" data-level="8.8" data-path="git-version-control.html"><a href="git-version-control.html#cloning-an-existing-project"><i class="fa fa-check"></i><b>8.8</b> Cloning an Existing Project</a></li>
<li class="chapter" data-level="8.9" data-path="git-version-control.html"><a href="git-version-control.html#keys"><i class="fa fa-check"></i><b>8.9</b> GitHub and SSH keys</a></li>
<li class="chapter" data-level="8.10" data-path="git-version-control.html"><a href="git-version-control.html#halftime-summary"><i class="fa fa-check"></i><b>8.10</b> Halftime Summary</a></li>
<li class="chapter" data-level="8.11" data-path="git-version-control.html"><a href="git-version-control.html#everyday-git-one-computer-no-collaboration"><i class="fa fa-check"></i><b>8.11</b> Everyday Git: One Computer, No Collaboration</a><ul>
<li class="chapter" data-level="8.11.1" data-path="git-version-control.html"><a href="git-version-control.html#commits"><i class="fa fa-check"></i><b>8.11.1</b> Commits</a></li>
<li class="chapter" data-level="8.11.2" data-path="git-version-control.html"><a href="git-version-control.html#status"><i class="fa fa-check"></i><b>8.11.2</b> Status</a></li>
<li class="chapter" data-level="8.11.3" data-path="git-version-control.html"><a href="git-version-control.html#the-file-.gitignore"><i class="fa fa-check"></i><b>8.11.3</b> The File <code>.gitignore</code></a></li>
<li class="chapter" data-level="8.11.4" data-path="git-version-control.html"><a href="git-version-control.html#log"><i class="fa fa-check"></i><b>8.11.4</b> Log</a></li>
<li class="chapter" data-level="8.11.5" data-path="git-version-control.html"><a href="git-version-control.html#diff"><i class="fa fa-check"></i><b>8.11.5</b> Diff</a></li>
</ul></li>
<li class="chapter" data-level="8.12" data-path="git-version-control.html"><a href="git-version-control.html#everyday-git-github-or-multiple-computers"><i class="fa fa-check"></i><b>8.12</b> Everyday Git: GitHub or Multiple Computers</a></li>
<li class="chapter" data-level="8.13" data-path="git-version-control.html"><a href="git-version-control.html#everyday-git-collaboration"><i class="fa fa-check"></i><b>8.13</b> Everyday Git: Collaboration</a><ul>
<li class="chapter" data-level="8.13.1" data-path="git-version-control.html"><a href="git-version-control.html#setup"><i class="fa fa-check"></i><b>8.13.1</b> Setup</a></li>
<li class="chapter" data-level="8.13.2" data-path="git-version-control.html"><a href="git-version-control.html#workflow"><i class="fa fa-check"></i><b>8.13.2</b> Workflow</a></li>
</ul></li>
<li class="chapter" data-level="8.14" data-path="git-version-control.html"><a href="git-version-control.html#wrapup"><i class="fa fa-check"></i><b>8.14</b> Wrapup</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Data Analysis with R &amp; Reproducible Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linear-regression-in-r" class="section level1">
<h1><span class="header-section-number"> 4</span> Linear Regression in R</h1>
<p><em>Author: Nathaniel E. Helwig</em></p>
<div id="chapter-outline-and-goals-1" class="section level2">
<h2><span class="header-section-number">4.1</span> Chapter Outline and Goals</h2>
<p>In this chapter, we will cover how to…</p>
<ul>
<li>Fit simple and multiple linear regression models</li>
<li>Test the significance of regression coefficients</li>
<li>Plot and interpret the regression results</li>
<li>Make predictions from fit regression models</li>
</ul>
<p>R’s <strong>lm</strong> (linear model) function will be the primary tool used in the chapter.</p>
</div>
<div id="minnesota-beer-data-reminder" class="section level2">
<h2><span class="header-section-number">4.2</span> Minnesota Beer Data (Reminder)</h2>
<div id="overview-2" class="section level3">
<h3><span class="header-section-number">4.2.1</span> Overview</h3>
<p>The Minnesota beer data has 44 beers measured on 7 variables:</p>
<ol style="list-style-type: decimal">
<li><em>Brewery</em>: Name of the brewery (<strong>factor</strong> with 8 levels)</li>
<li><em>Beer</em>: Name of the beer (<strong>factor</strong> with 44 levels)</li>
<li><em>Description</em>: Description of the beer (<strong>factor</strong> with 37 levels)</li>
<li><em>Style</em>: Style of the beer (<strong>factor</strong> with 3 levels)</li>
<li><em>ABV</em>: Alcohol by volume (<strong>numeric</strong>)</li>
<li><em>IBU</em>: International bitterness units (<strong>integer</strong>)</li>
<li><em>Rating</em>: Beer Advocate rating (<strong>integer</strong>)</li>
</ol>
<p>Data obtained by NEH from <a href="http://beeradvocate.com">Beer Advocate</a> and the websites of the eight breweries.</p>
</div>
<div id="load-and-look-at-the-data" class="section level3">
<h3><span class="header-section-number">4.2.2</span> Load and Look at the Data</h3>
<p>Use the <strong>read.csv</strong> function to load the <em>beer</em> data into R</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">beer &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;http://users.stat.umn.edu/~helwig/notes/MNbeer.csv&quot;</span>)</code></pre></div>
<p>The <strong>head</strong> function returns the first six lines of a data frame</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(beer)</code></pre></div>
<pre><code>##       Brewery         Beer              Description Style ABV IBU Rating
## 1     Bauhaus  Wonderstuff     New Bohemian Pilsner Lager 5.4  48     88
## 2     Bauhaus    Stargazer German Style Schwarzbier Lager 5.0  28     87
## 3     Bauhaus  Wagon Party    West Cost Style Lager Lager 5.4  55     86
## 4     Bauhaus    Sky-Five!        Midwest Coast IPA   IPA 6.7  70     86
## 5 Bent Paddle         Kanu         Session Pale Ale   Ale 4.8  48     85
## 6 Bent Paddle Venture Pils            Pilsner Lager Lager 5.0  38     87</code></pre>
</div>
</div>
<div id="simple-linear-regression" class="section level2">
<h2><span class="header-section-number">4.3</span> Simple Linear Regression</h2>
<div id="fit-the-model" class="section level3">
<h3><span class="header-section-number">4.3.1</span> Fit the Model</h3>
<p>Consider a simple linear regression model of the form <span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \epsilon_i
\]</span> where <span class="math inline">\(y_i\)</span> is the Rating of the <em>i</em>-th beer (response), <span class="math inline">\(x_i\)</span> is the ABV of the <em>i</em>-th beer (predictor), <span class="math inline">\(\beta_0\)</span> is the unknown regression intercept, <span class="math inline">\(\beta_1\)</span> is the unknown regression slope, and <span class="math inline">\(\epsilon_i \sim \mathrm{N}(0, \sigma^2)\)</span> is a latent Gaussian error term. To fit the model, we can use the <strong>lm</strong> function</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod &lt;-<span class="st"> </span><span class="kw">lm</span>(Rating <span class="op">~</span><span class="st"> </span>ABV, <span class="dt">data =</span> beer)</code></pre></div>
<p>The first input is the regression formula (Response ~ Predictor), and the second input is the data frame containing the variables in the regression formula. Note that <em>mod</em> is an object of class <em>lm</em>, which is a list containing information about the fit model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(mod)</code></pre></div>
<pre><code>## [1] &quot;lm&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(mod)</code></pre></div>
<pre><code>##  [1] &quot;coefficients&quot;  &quot;residuals&quot;     &quot;effects&quot;       &quot;rank&quot;         
##  [5] &quot;fitted.values&quot; &quot;assign&quot;        &quot;qr&quot;            &quot;df.residual&quot;  
##  [9] &quot;xlevels&quot;       &quot;call&quot;          &quot;terms&quot;         &quot;model&quot;</code></pre>
<p>For example, the <em>$coefficients</em> element contains the estimated regression coefficients</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod<span class="op">$</span>coefficients</code></pre></div>
<pre><code>## (Intercept)         ABV 
##   74.034788    2.259646</code></pre>
<p>which reveal that the expected Rating increases by about 2.26 points for every 1 unit (i.e., 1%) increaese in ABV.</p>
</div>
<div id="inference-information" class="section level3">
<h3><span class="header-section-number">4.3.2</span> Inference Information</h3>
<p>To obtain a more detailed summary of the fit model, use the <strong>summary</strong> function</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">modsum &lt;-<span class="st"> </span><span class="kw">summary</span>(mod)
<span class="kw">names</span>(modsum)</code></pre></div>
<pre><code>##  [1] &quot;call&quot;          &quot;terms&quot;         &quot;residuals&quot;     &quot;coefficients&quot; 
##  [5] &quot;aliased&quot;       &quot;sigma&quot;         &quot;df&quot;            &quot;r.squared&quot;    
##  [9] &quot;adj.r.squared&quot; &quot;fstatistic&quot;    &quot;cov.unscaled&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">modsum</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Rating ~ ABV, data = beer)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.4965 -2.1563  0.3593  1.6670  7.0179 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  74.0348     3.5933  20.604  &lt; 2e-16 ***
## ABV           2.2596     0.6117   3.694 0.000632 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.28 on 42 degrees of freedom
## Multiple R-squared:  0.2452, Adjusted R-squared:  0.2272 
## F-statistic: 13.65 on 1 and 42 DF,  p-value: 0.000632</code></pre>
<p>Note that summarizing an <em>lm</em> object returns the estimated error standard deviation <em>sigma</em> (<span class="math inline">\(\hat{\sigma} = 3.28\)</span>), the coefficient of determination <em>r.squared</em> (<span class="math inline">\(R^2 = 0.2452\)</span>), and a <em>coefficient</em> inference table for testing <span class="math inline">\(H_0: \beta_j = 0\)</span> versus <span class="math inline">\(H_1: \beta_j \neq 0\)</span>. The observed <em>t</em> statistic for testing the slope parameter is <span class="math inline">\(t = 3.69\)</span> with 42 degrees of freedom, resulting in a p-value less than 0.001—we reject <span class="math inline">\(H_0\)</span> using any standard <span class="math inline">\(\alpha\)</span> level.</p>
<p>Use the <strong>confint</strong> function to obtain confidence intervals for regression coefficients</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confint</span>(mod, <span class="st">&quot;ABV&quot;</span>)</code></pre></div>
<pre><code>##        2.5 %   97.5 %
## ABV 1.025152 3.494139</code></pre>
<p>The 95% confidence interval for <span class="math inline">\(\beta_1\)</span> reveals that we expect the average Rating to increase by 1.03 to 3.49 points for each additional 1% ABV.</p>
</div>
<div id="plot-the-regression-line" class="section level3">
<h3><span class="header-section-number">4.3.3</span> Plot the Regression Line</h3>
<p>It’s easy to include the least-squares regression line on a scatterplot by adding a <code>geom_smooth()</code> to the <code>ggplot()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Without &quot;standard error bars&quot;</span>
<span class="kw">ggplot</span>(beer, <span class="kw">aes</span>(<span class="dt">x =</span> IBU, <span class="dt">y =</span> ABV)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>)</code></pre></div>
<p><img src="04-LinReg_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># With &quot;standard error bars&quot;</span>
<span class="kw">ggplot</span>(beer, <span class="kw">aes</span>(<span class="dt">x =</span> IBU, <span class="dt">y =</span> ABV)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">TRUE</span>)</code></pre></div>
<p><img src="04-LinReg_files/figure-html/unnamed-chunk-9-2.png" width="672" /></p>
<p>```</p>
<p>Alternatively, we can use the <strong>abline()</strong> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(beer<span class="op">$</span>ABV, beer<span class="op">$</span>Rating, <span class="dt">xlab =</span> <span class="st">&quot;Alcohol By Volume&quot;</span>, 
     <span class="dt">ylab =</span> <span class="st">&quot;Beer Advocate Rating&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;Alcohol by Rating&quot;</span>)
<span class="kw">abline</span>(mod)</code></pre></div>
<p><img src="04-LinReg_files/figure-html/unnamed-chunk-10-1.png" width="480" style="display: block; margin: auto;" /></p>
</div>
<div id="diagnostic-and-influence-plots" class="section level3">
<h3><span class="header-section-number">4.3.4</span> Diagnostic and Influence Plots</h3>
<p>R makes it really easy to create simple diagnostic and influence plots for a fit regression model:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(mod)</code></pre></div>
<p><img src="04-LinReg_files/figure-html/unnamed-chunk-11-1.png" width="480" style="display: block; margin: auto;" /><img src="04-LinReg_files/figure-html/unnamed-chunk-11-2.png" width="480" style="display: block; margin: auto;" /><img src="04-LinReg_files/figure-html/unnamed-chunk-11-3.png" width="480" style="display: block; margin: auto;" /><img src="04-LinReg_files/figure-html/unnamed-chunk-11-4.png" width="480" style="display: block; margin: auto;" /></p>
</div>
<div id="prediction-for-new-data" class="section level3">
<h3><span class="header-section-number">4.3.5</span> Prediction for New Data</h3>
<p>We often want to use a fit regression model to create predictions for new data. In R, this involves first creating the data frame of new predictor scores</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">newdata &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">ABV =</span> <span class="kw">seq</span>(<span class="fl">4.2</span>, <span class="fl">7.5</span>, <span class="dt">by =</span> <span class="fl">0.1</span>))</code></pre></div>
<p>which we input to the <strong>predict</strong> function along with the fit model</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">newfit &lt;-<span class="st"> </span><span class="kw">predict</span>(mod, newdata)
newfit</code></pre></div>
<pre><code>##        1        2        3        4        5        6        7        8 
## 83.52530 83.75127 83.97723 84.20319 84.42916 84.65512 84.88109 85.10705 
##        9       10       11       12       13       14       15       16 
## 85.33302 85.55898 85.78495 86.01091 86.23688 86.46284 86.68880 86.91477 
##       17       18       19       20       21       22       23       24 
## 87.14073 87.36670 87.59266 87.81863 88.04459 88.27056 88.49652 88.72249 
##       25       26       27       28       29       30       31       32 
## 88.94845 89.17441 89.40038 89.62634 89.85231 90.07827 90.30424 90.53020 
##       33       34 
## 90.75617 90.98213</code></pre>
<p>By default, the <strong>predict</strong> function returns a vector of predictions <span class="math inline">\(\hat{y}_{i(\mbox{new})} = \hat{\beta}_0 + \hat{\beta}_1 x_{i(\mbox{new})}\)</span>. To obtain the corresponding standard errors of the predictions, we can use the <em>se.fit</em> input</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">newfitse &lt;-<span class="st"> </span><span class="kw">predict</span>(mod, newdata, <span class="dt">se.fit =</span> <span class="ot">TRUE</span>)
newfitse</code></pre></div>
<pre><code>## $fit
##        1        2        3        4        5        6        7        8 
## 83.52530 83.75127 83.97723 84.20319 84.42916 84.65512 84.88109 85.10705 
##        9       10       11       12       13       14       15       16 
## 85.33302 85.55898 85.78495 86.01091 86.23688 86.46284 86.68880 86.91477 
##       17       18       19       20       21       22       23       24 
## 87.14073 87.36670 87.59266 87.81863 88.04459 88.27056 88.49652 88.72249 
##       25       26       27       28       29       30       31       32 
## 88.94845 89.17441 89.40038 89.62634 89.85231 90.07827 90.30424 90.53020 
##       33       34 
## 90.75617 90.98213 
## 
## $se.fit
##         1         2         3         4         5         6         7 
## 1.1064827 1.0521132 0.9985311 0.9458702 0.8942934 0.8439992 0.7952311 
##         8         9        10        11        12        13        14 
## 0.7482877 0.7035342 0.6614152 0.6224659 0.5873171 0.5566893 0.5313647 
##        15        16        17        18        19        20        21 
## 0.5121308 0.4996912 0.4945590 0.4969606 0.5067890 0.5236260 0.5468247 
##        22        23        24        25        26        27        28 
## 0.5756164 0.6092087 0.6468540 0.6878872 0.7317387 0.7779320 0.8260744 
##        29        30        31        32        33        34 
## 0.8758444 0.9269800 0.9792672 1.0325312 1.0866283 1.1414400 
## 
## $df
## [1] 42
## 
## $residual.scale
## [1] 3.279704</code></pre>
<p>The <em>interval</em> input can be used to create confidence and prediction intervals</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">newfitCI &lt;-<span class="st"> </span><span class="kw">predict</span>(mod, newdata, <span class="dt">interval =</span> <span class="st">&quot;confidence&quot;</span>)
newfitPI &lt;-<span class="st"> </span><span class="kw">predict</span>(mod, newdata, <span class="dt">interval =</span> <span class="st">&quot;prediction&quot;</span>)
<span class="kw">head</span>(newfitCI)</code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 83.52530 81.29233 85.75827
## 2 83.75127 81.62801 85.87452
## 3 83.97723 81.96211 85.99235
## 4 84.20319 82.29435 86.11204
## 5 84.42916 82.62440 86.23392
## 6 84.65512 82.95186 86.35838</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(newfitPI)</code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 83.52530 76.54007 90.51053
## 2 83.75127 76.80033 90.70220
## 3 83.97723 77.05856 90.89590
## 4 84.20319 77.31472 91.09166
## 5 84.42916 77.56880 91.28951
## 6 84.65512 77.82077 91.48948</code></pre>
<p>The confidence and prediction intervals can be plotted using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Confidence intervals</span>
<span class="kw">ggplot</span>(beer, <span class="kw">aes</span>(<span class="dt">x =</span> ABV, <span class="dt">y =</span> Rating)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">TRUE</span>)</code></pre></div>
<p><img src="04-LinReg_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Prediction intervals</span>
newfitPI &lt;-<span class="st"> </span><span class="kw">data.frame</span>(newfitPI)
newfitPI<span class="op">$</span>ABV &lt;-<span class="st"> </span>newdata<span class="op">$</span>ABV
<span class="kw">ggplot</span>(beer, <span class="kw">aes</span>(<span class="dt">x =</span> ABV, <span class="dt">y =</span> Rating)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_ribbon</span>(<span class="dt">data =</span> newfitPI, <span class="kw">aes</span>(<span class="dt">x =</span> ABV, <span class="dt">y =</span> fit, <span class="dt">ymin =</span> lwr, <span class="dt">ymax =</span> upr), <span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.2</span>) </code></pre></div>
<p><img src="04-LinReg_files/figure-html/unnamed-chunk-16-2.png" width="672" /></p>
<p>Or:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(beer<span class="op">$</span>ABV, beer<span class="op">$</span>Rating, <span class="dt">xlab =</span> <span class="st">&quot;Alcohol By Volume&quot;</span>, 
     <span class="dt">ylab =</span> <span class="st">&quot;Beer Advocate Rating&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;Alcohol by Rating&quot;</span>,
     <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">75</span>, <span class="dv">100</span>))
<span class="kw">lines</span>(newdata<span class="op">$</span>ABV, newfitCI[,<span class="dv">1</span>])
<span class="kw">lines</span>(newdata<span class="op">$</span>ABV, newfitCI[,<span class="dv">2</span>], <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)
<span class="kw">lines</span>(newdata<span class="op">$</span>ABV, newfitCI[,<span class="dv">3</span>], <span class="dt">lty =</span> <span class="dv">2</span>, <span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)
<span class="kw">lines</span>(newdata<span class="op">$</span>ABV, newfitPI[,<span class="dv">2</span>], <span class="dt">lty =</span> <span class="dv">3</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)
<span class="kw">lines</span>(newdata<span class="op">$</span>ABV, newfitPI[,<span class="dv">3</span>], <span class="dt">lty =</span> <span class="dv">3</span>, <span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)
<span class="kw">legend</span>(<span class="st">&quot;bottomright&quot;</span>, <span class="dt">lty =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">3</span>, <span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;fit&quot;</span>, <span class="st">&quot;95% CI&quot;</span>, <span class="st">&quot;95% PI&quot;</span>),
       <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;red&quot;</span>), <span class="dt">bty =</span> <span class="st">&quot;n&quot;</span>)</code></pre></div>
<p><img src="04-LinReg_files/figure-html/unnamed-chunk-17-1.png" width="480" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="multiple-linear-regression" class="section level2">
<h2><span class="header-section-number">4.4</span> Multiple Linear Regression</h2>
<div id="overview-3" class="section level3">
<h3><span class="header-section-number">4.4.1</span> Overview</h3>
<p>A multiple linear regression model has the form <span class="math display">\[
y_i = \beta_0 + \sum_{j=1}^p \beta_j x_{ij} + \epsilon_i
\]</span> where <span class="math inline">\(y_i\)</span> is the response for the <span class="math inline">\(i\)</span>-th observation, <span class="math inline">\(x_{ij}\)</span> is the <em>j</em>-th predictor for the <em>i</em>-th observation, <span class="math inline">\(\beta_0\)</span> is the unknown regression intercept, <span class="math inline">\(\beta_j\)</span> is the unknown regression slope for the <em>j</em>-th predictor, and <span class="math inline">\(\epsilon_i \sim \mathrm{N}(0, \sigma^2)\)</span> is a latent Gaussian error term. Note that <span class="math inline">\(\beta_j\)</span> gives the expected change in the response variable for a 1-unit change in the <em>j</em>-th predictor variable conditioned on the other predictors, i.e., holding all other predictors constant.</p>
</div>
<div id="additive-effects" class="section level3">
<h3><span class="header-section-number">4.4.2</span> Additive Effects</h3>
<p>We will start by considering a model predicting the Rating from the additive effects of ABV and Brewery</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">amod &lt;-<span class="st"> </span><span class="kw">lm</span>(Rating <span class="op">~</span><span class="st"> </span>ABV <span class="op">+</span><span class="st"> </span>Brewery, <span class="dt">data =</span> beer)</code></pre></div>
<p>Note that this model allows each Brewery to have a unique regression intercept (Bauhaus is the baseline), but assumes that the slope between ABV and Rating is the same for each Brewery. We can summarize the model using the same approach as before:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">amodsum &lt;-<span class="st"> </span><span class="kw">summary</span>(amod)
amodsum</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Rating ~ ABV + Brewery, data = beer)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -4.702 -1.477  0.217  1.207  5.505 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          77.82164    3.27842  23.738  &lt; 2e-16 ***
## ABV                   1.58726    0.53419   2.971  0.00533 ** 
## BreweryBent Paddle    1.01666    1.75996   0.578  0.56719    
## BreweryFulton        -2.27857    1.75923  -1.295  0.20373    
## BreweryIndeed         0.87472    1.64545   0.532  0.59836    
## BrewerySteel Toe      0.05955    1.89701   0.031  0.97513    
## BrewerySummit        -1.16837    1.64440  -0.711  0.48209    
## BrewerySurly          4.25343    1.68773   2.520  0.01644 *  
## BreweryUrban Growler -3.22777    1.76155  -1.832  0.07542 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.622 on 35 degrees of freedom
## Multiple R-squared:  0.5979, Adjusted R-squared:  0.506 
## F-statistic: 6.506 on 8 and 35 DF,  p-value: 3.502e-05</code></pre>
<p>Compared to the simple linear regression model containing only the ABV predictor, we have noticeably reduced the residual standard deviation estimate <em>sigma</em> (<span class="math inline">\(\hat{\sigma} = 2.622\)</span>) and increased the coefficient of (multiple) determination <em>r.squared</em> (<span class="math inline">\(R^2 = 0.5979\)</span>).</p>
<p>The <strong>anova</strong> and <strong>Anova</strong> functions can be used to test the significance of terms</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(car)</code></pre></div>
<pre><code>## Loading required package: carData</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(amod)  <span class="co"># Type I (sequential) SS test</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: Rating
##           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
## ABV        1 146.77 146.774 21.3451 5.026e-05 ***
## Brewery    7 211.10  30.157  4.3857  0.001393 ** 
## Residuals 35 240.67   6.876                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">Anova</span>(amod)  <span class="co"># Type II SS test</span></code></pre></div>
<pre><code>## Anova Table (Type II tests)
## 
## Response: Rating
##            Sum Sq Df F value   Pr(&gt;F)   
## ABV        60.709  1  8.8288 0.005331 **
## Brewery   211.102  7  4.3857 0.001393 **
## Residuals 240.669 35                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Note that <strong>anova</strong> tests the effects sequentially (ABV alone, then Brewery given ABV), whereas the <strong>Anova</strong> function (in the <em>car</em> package) tests the effects conditioned on the other effect (ABV given Brewery, Brewery given ABV). Using the Type II tests from the <strong>Anova</strong> function, we see that both ABV (<span class="math inline">\(F_{1,35} = 8.83, p = 0.005\)</span>) and Brewery (<span class="math inline">\(F_{7,35} = 4.39, p = 0.001\)</span>) significantly add to the prediction of the beer’s Rating.</p>
</div>
<div id="interaction-effects" class="section level3">
<h3><span class="header-section-number">4.4.3</span> Interaction Effects</h3>
<p>Next we consider a model predicting the Rating from the interaction effects of ABV and Brewery</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">imod &lt;-<span class="st"> </span><span class="kw">lm</span>(Rating <span class="op">~</span><span class="st"> </span>ABV <span class="op">*</span><span class="st"> </span>Brewery, <span class="dt">data =</span> beer)</code></pre></div>
<p>Note that formula notation is shorthand for <em>Rating ~ ABV + Brewery + ABV:Brewery</em>, so this model allows each Brewery to have a unique regression intercept and slope relating ABV and Rating. We can summarize the model using the same approach as before:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">imodsum &lt;-<span class="st"> </span><span class="kw">summary</span>(imod)
imodsum</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Rating ~ ABV * Brewery, data = beer)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.2905 -1.3040 -0.0471  1.4774  4.9434 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)               90.4203    12.4097   7.286 6.22e-08 ***
## ABV                       -0.6525     2.1920  -0.298    0.768    
## BreweryBent Paddle       -17.0655    17.8235  -0.957    0.347    
## BreweryFulton            -18.8852    14.6059  -1.293    0.207    
## BreweryIndeed             -8.1702    14.4123  -0.567    0.575    
## BrewerySteel Toe         -16.6529    16.6037  -1.003    0.324    
## BrewerySummit            -11.2505    15.7834  -0.713    0.482    
## BrewerySurly             -12.0484    14.6792  -0.821    0.419    
## BreweryUrban Growler      -8.6554    19.7273  -0.439    0.664    
## ABV:BreweryBent Paddle     3.2331     3.1819   1.016    0.318    
## ABV:BreweryFulton          2.9580     2.5806   1.146    0.261    
## ABV:BreweryIndeed          1.6240     2.5265   0.643    0.526    
## ABV:BrewerySteel Toe       2.8851     2.7839   1.036    0.309    
## ABV:BrewerySummit          1.7846     2.8071   0.636    0.530    
## ABV:BrewerySurly           2.8236     2.5109   1.125    0.270    
## ABV:BreweryUrban Growler   1.0034     3.4276   0.293    0.772    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.813 on 28 degrees of freedom
## Multiple R-squared:  0.6297, Adjusted R-squared:  0.4313 
## F-statistic: 3.174 on 15 and 28 DF,  p-value: 0.004029</code></pre>
<p>Compared to the additive model, we have slightly increased the residual standard deviation estimate <em>sigma</em> (<span class="math inline">\(\hat{\sigma} = 2.813\)</span>) and increased the coefficient of (multiple) determination <em>r.squared</em> (<span class="math inline">\(R^2 = 0.6297\)</span>).</p>
<p>Use the <strong>Anova</strong> function to test the signifiance of the effects</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(car)
<span class="kw">Anova</span>(imod)  <span class="co"># Type II SS test</span></code></pre></div>
<pre><code>## Anova Table (Type II tests)
## 
## Response: Rating
##              Sum Sq Df F value   Pr(&gt;F)   
## ABV          60.709  1  7.6695 0.009854 **
## Brewery     211.102  7  3.8098 0.005009 **
## ABV:Brewery  19.030  7  0.3434 0.926653   
## Residuals   221.639 28                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The results reveal that the interaction effect is not significant (<span class="math inline">\(F_{7,28} = 0.34, p = 0.927\)</span>), but the main effects of ABV (<span class="math inline">\(F_{1,28} = 7.67, p = 0.01\)</span>) and Brewery (<span class="math inline">\(F_{7,28} = 3.81, p = 0.005\)</span>) are significant at the classic <span class="math inline">\(\alpha = 0.05\)</span> significance level.</p>
</div>
<div id="comparing-fit-models" class="section level3">
<h3><span class="header-section-number">4.4.4</span> Comparing Fit Models</h3>
<p>To compare the fit models, we can use the <strong>anova</strong> function for <em>F</em>-tests</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(mod, amod, imod)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: Rating ~ ABV
## Model 2: Rating ~ ABV + Brewery
## Model 3: Rating ~ ABV * Brewery
##   Res.Df    RSS Df Sum of Sq      F   Pr(&gt;F)   
## 1     42 451.77                                
## 2     35 240.67  7    211.10 3.8098 0.005009 **
## 3     28 221.64  7     19.03 0.3434 0.926653   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>or the <strong>AIC</strong> function to extract Akaike’s information criterion</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">AIC</span>(mod, amod, imod)</code></pre></div>
<pre><code>##      df      AIC
## mod   3 233.3420
## amod 10 219.6329
## imod 17 230.0085</code></pre>
<p>In this case, the <em>F</em>-tests and AIC values suggest that the additive model should be preferred. We conclude that each Brewery has a unique baseline Rating, and increasing the ABV by 1% corresponds to an expected 1.59 point increase in the Rating.</p>
</div>
</div>
<div id="exercises-3" class="section level2">
<h2><span class="header-section-number">4.5</span> Exercises</h2>
<ol style="list-style-type: decimal">
<li>Load the Minnesota Beer Data into R.</li>
<li>Make a scatterplot of the IBU (x-axis) by Rating (y-axis)</li>
<li>Fit a simple linear regression model predicting Rating from IBU.</li>
<li>Is there a significant linear relationship between IBU and Rating?</li>
<li>Plot the linear relationship, along with 95% confidence and prediction intervals.</li>
<li>Fit a multiple linear regression model predicting Rating from the additive effects of IBU and Brewery.</li>
<li>Fit a multiple linear regression model predicting Rating from the additive and interaction effects of IBU and Brewery.</li>
<li>Considering the models you fit in Ex 3, 7, 8, which do you prefer and why?</li>
</ol>
<p><br />
<br />
<br />
</p>
<p><strong>Solutions:</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## 1: Load the Minnesota Beer Data into R
beer &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;http://users.stat.umn.edu/~helwig/notes/MNbeer.csv&quot;</span>)

<span class="co"># 2: Make a scatterplot of the IBU (x-axis) by Rating (y-axis)</span>
<span class="kw">ggplot</span>(beer, <span class="kw">aes</span>(<span class="dt">x =</span> IBU, <span class="dt">y =</span> Rating)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>()</code></pre></div>
<p><img src="04-LinReg_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># 3: Fit a simple linear regression model predicting Rating from IBU</span>
<span class="co"># For every 1 IBU increase, Rating tends to increase by 0.07 points.</span>
my_model &lt;-<span class="st"> </span><span class="kw">lm</span>(Rating <span class="op">~</span><span class="st"> </span>IBU, <span class="dt">data =</span> beer)
<span class="kw">coef</span>(my_model)</code></pre></div>
<pre><code>## (Intercept)         IBU 
## 83.76336277  0.06693905</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#4: Is there a significant linear relationship between IBU and Rating?</span>
<span class="co"># Answer: Yes!  Notice that the p-value in the IBU row</span>
<span class="co"># below is 0.  Also, notice that the confidence bands below</span>
<span class="co"># don&#39;t include the flat, 0 slope line.</span>
<span class="kw">summary</span>(my_model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Rating ~ IBU, data = beer)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.3822 -2.4669  0.3309  2.0854  9.8856 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 83.76336    1.36811  61.225   &lt;2e-16 ***
## IBU          0.06694    0.02474   2.706   0.0098 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.484 on 42 degrees of freedom
## Multiple R-squared:  0.1485, Adjusted R-squared:  0.1282 
## F-statistic: 7.322 on 1 and 42 DF,  p-value: 0.0098</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#5: Plot the linear relationship, along with 95% confidence and prediction intervals</span>
<span class="co"># The confidence intervals reflect the plausible TREND in this relationship.</span>
<span class="co"># The prediction intervals reflect the plausible DEVIATIONS from this trend.</span>
<span class="kw">ggplot</span>(beer, <span class="kw">aes</span>(<span class="dt">x =</span> IBU, <span class="dt">y =</span> Rating)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">TRUE</span>)</code></pre></div>
<p><img src="04-LinReg_files/figure-html/unnamed-chunk-26-2.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># prediction bands (this code = yuck)</span>
newdata  &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">IBU =</span> <span class="kw">seq</span>(<span class="dv">15</span>, <span class="dv">100</span>, <span class="dt">by =</span> <span class="dv">1</span>))
newfit   &lt;-<span class="st"> </span><span class="kw">predict</span>(my_model, newdata)
newfitPI &lt;-<span class="st"> </span><span class="kw">predict</span>(my_model, newdata, <span class="dt">interval =</span> <span class="st">&quot;prediction&quot;</span>)
newfitPI &lt;-<span class="st"> </span><span class="kw">data.frame</span>(newfitPI)
newfitPI<span class="op">$</span>IBU &lt;-<span class="st"> </span>newdata<span class="op">$</span>IBU
<span class="kw">ggplot</span>(beer, <span class="kw">aes</span>(<span class="dt">x =</span> IBU, <span class="dt">y =</span> Rating)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_ribbon</span>(<span class="dt">data =</span> newfitPI, <span class="kw">aes</span>(<span class="dt">x =</span> IBU, <span class="dt">y =</span> fit, <span class="dt">ymin =</span> lwr, <span class="dt">ymax =</span> upr), <span class="dt">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="dt">alpha =</span> <span class="fl">0.2</span>) </code></pre></div>
<pre><code>## Warning: Ignoring unknown aesthetics: y</code></pre>
<p><img src="04-LinReg_files/figure-html/unnamed-chunk-26-3.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#6: Fit a multiple linear regression model predicting Rating from the additive effects of IBU and Brewery.</span>
model_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(Rating <span class="op">~</span><span class="st"> </span>IBU <span class="op">+</span><span class="st"> </span>Brewery, <span class="dt">data =</span> beer)
<span class="kw">summary</span>(model_<span class="dv">2</span>)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Rating ~ IBU + Brewery, data = beer)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.7732 -1.7126  0.0889  1.2031  5.9521 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          83.98984    1.65525  50.741  &lt; 2e-16 ***
## IBU                   0.05493    0.01969   2.790  0.00848 ** 
## BreweryBent Paddle    1.19330    1.78467   0.669  0.50811    
## BreweryFulton        -2.00670    1.78467  -1.124  0.26849    
## BreweryIndeed         0.46958    1.67917   0.280  0.78139    
## BrewerySteel Toe      1.16761    1.87697   0.622  0.53793    
## BrewerySummit        -1.47248    1.66443  -0.885  0.38237    
## BrewerySurly          5.20257    1.66495   3.125  0.00357 ** 
## BreweryUrban Growler -2.59571    1.78495  -1.454  0.15479    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.654 on 35 degrees of freedom
## Multiple R-squared:  0.5881, Adjusted R-squared:  0.4939 
## F-statistic: 6.246 on 8 and 35 DF,  p-value: 5.108e-05</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#7: Fit a multiple linear regression model predicting Rating from the additive and interaction effects of IBU and Brewery.</span>
model_<span class="dv">3</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(Rating <span class="op">~</span><span class="st"> </span>IBU <span class="op">*</span><span class="st"> </span>Brewery, <span class="dt">data =</span> beer)
<span class="kw">summary</span>(model_<span class="dv">3</span>)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Rating ~ IBU * Brewery, data = beer)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.1925 -1.5054 -0.0439  1.1809  5.4490 
## 
## Coefficients:
##                          Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              88.22268    4.88650  18.054   &lt;2e-16 ***
## IBU                      -0.02931    0.09313  -0.315    0.755    
## BreweryBent Paddle       -1.02635    6.56017  -0.156    0.877    
## BreweryFulton            -6.97752    5.59517  -1.247    0.223    
## BreweryIndeed            -2.02179    5.70948  -0.354    0.726    
## BrewerySteel Toe         -4.66505    5.96999  -0.781    0.441    
## BrewerySummit            -6.14258    5.99866  -1.024    0.315    
## BrewerySurly             -1.26059    5.52626  -0.228    0.821    
## BreweryUrban Growler     -4.71814    5.99284  -0.787    0.438    
## IBU:BreweryBent Paddle    0.03848    0.13323   0.289    0.775    
## IBU:BreweryFulton         0.10101    0.10813   0.934    0.358    
## IBU:BreweryIndeed         0.05608    0.10323   0.543    0.591    
## IBU:BrewerySteel Toe      0.11515    0.11102   1.037    0.309    
## IBU:BrewerySummit         0.09249    0.11216   0.825    0.417    
## IBU:BrewerySurly          0.12576    0.10291   1.222    0.232    
## IBU:BreweryUrban Growler  0.03605    0.11883   0.303    0.764    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.814 on 28 degrees of freedom
## Multiple R-squared:  0.6297, Adjusted R-squared:  0.4313 
## F-statistic: 3.174 on 15 and 28 DF,  p-value: 0.00403</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(beer, <span class="kw">aes</span>(<span class="dt">x =</span> IBU, <span class="dt">y =</span> Rating, <span class="dt">color =</span> Brewery)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="dt">se =</span> <span class="ot">FALSE</span>)</code></pre></div>
<p><img src="04-LinReg_files/figure-html/unnamed-chunk-26-4.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#8 Considering the models you fit in Ex 3, 7, 8, which do you prefer and why?</span>
<span class="co"># I prefer the middle model.  Including Brewery in the model appears</span>
<span class="co"># to improve predictions.  The &quot;interactive&quot; effects seem to be overkill.</span></code></pre></div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="simple-statistics-in-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="logistic-regression-in-r.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"download": null,
"toc": {
"collapse": "section",
"depth": 2,
"scroll_highlight": true
},
"toolbar": {
"position": "fixed"
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
