<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Introduction to Data Analysis with R &amp; Reproducible Data Science</title>
  <meta name="description" content="Introduction to Data Analysis with R &amp; Reproducible Data Science">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Introduction to Data Analysis with R &amp; Reproducible Data Science" />
  <meta property="og:type" content="book" />
  
  
  
  <meta name="github-repo" content="IRSAAtUMn/RWorkshop18/docs" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Introduction to Data Analysis with R &amp; Reproducible Data Science" />
  
  
  

<meta name="author" content="Institute for Research in Statistics and its Applications at the University of Minnesota">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="linear-regression-in-r.html">
<link rel="next" href="using-r-reproducibly.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.2/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.4/datatables.js"></script>
<link href="libs/dt-core-1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.16/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.16/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Home</a></li>
<li class="chapter" data-level="1" data-path="introduction-to-r-rstudio.html"><a href="introduction-to-r-rstudio.html"><i class="fa fa-check"></i><b>1</b> Introduction to R &amp; RStudio</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-r-rstudio.html"><a href="introduction-to-r-rstudio.html#getting-started"><i class="fa fa-check"></i><b>1.1</b> Getting Started</a></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-r-rstudio.html"><a href="introduction-to-r-rstudio.html#basic-features"><i class="fa fa-check"></i><b>1.2</b> Basic features</a></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-r-rstudio.html"><a href="introduction-to-r-rstudio.html#getting-help"><i class="fa fa-check"></i><b>1.3</b> Getting Help</a></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-r-rstudio.html"><a href="introduction-to-r-rstudio.html#working-with-data"><i class="fa fa-check"></i><b>1.4</b> Working with data</a></li>
<li class="chapter" data-level="1.5" data-path="introduction-to-r-rstudio.html"><a href="introduction-to-r-rstudio.html#exercises"><i class="fa fa-check"></i><b>1.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>2</b> Data Visualization</a><ul>
<li class="chapter" data-level="2.1" data-path="data-visualization.html"><a href="data-visualization.html#ggplot"><i class="fa fa-check"></i><b>2.1</b> ggplot</a></li>
<li class="chapter" data-level="2.2" data-path="data-visualization.html"><a href="data-visualization.html#univariate-visualizations"><i class="fa fa-check"></i><b>2.2</b> Univariate visualizations</a></li>
<li class="chapter" data-level="2.3" data-path="data-visualization.html"><a href="data-visualization.html#visualizing-relationships"><i class="fa fa-check"></i><b>2.3</b> Visualizing Relationships</a></li>
<li class="chapter" data-level="2.4" data-path="data-visualization.html"><a href="data-visualization.html#exercises-1"><i class="fa fa-check"></i><b>2.4</b> Exercises</a></li>
<li class="chapter" data-level="2.5" data-path="data-visualization.html"><a href="data-visualization.html#extra"><i class="fa fa-check"></i><b>2.5</b> Extra</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html"><i class="fa fa-check"></i><b>3</b> Simple Statistics in R</a><ul>
<li class="chapter" data-level="3.1" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#chapter-outline-and-goals"><i class="fa fa-check"></i><b>3.1</b> Chapter Outline and Goals</a></li>
<li class="chapter" data-level="3.2" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#minnesota-beer-data"><i class="fa fa-check"></i><b>3.2</b> Minnesota Beer Data</a><ul>
<li class="chapter" data-level="3.2.1" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#overview"><i class="fa fa-check"></i><b>3.2.1</b> Overview</a></li>
<li class="chapter" data-level="3.2.2" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#load-the-data"><i class="fa fa-check"></i><b>3.2.2</b> Load the Data</a></li>
<li class="chapter" data-level="3.2.3" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#look-at-the-data"><i class="fa fa-check"></i><b>3.2.3</b> Look at the Data</a></li>
<li class="chapter" data-level="3.2.4" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#plot-the-data"><i class="fa fa-check"></i><b>3.2.4</b> Plot the Data</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#descriptive-statistics-in-r"><i class="fa fa-check"></i><b>3.3</b> Descriptive Statistics in R</a><ul>
<li class="chapter" data-level="3.3.1" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#overview-1"><i class="fa fa-check"></i><b>3.3.1</b> Overview</a></li>
<li class="chapter" data-level="3.3.2" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#minimum-and-maximum"><i class="fa fa-check"></i><b>3.3.2</b> Minimum and Maximum</a></li>
<li class="chapter" data-level="3.3.3" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#mean-standard-deviation-and-variance"><i class="fa fa-check"></i><b>3.3.3</b> Mean, Standard Deviation, and Variance</a></li>
<li class="chapter" data-level="3.3.4" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#medians-and-quantiles"><i class="fa fa-check"></i><b>3.3.4</b> Medians and Quantiles</a></li>
<li class="chapter" data-level="3.3.5" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#factor-level-information"><i class="fa fa-check"></i><b>3.3.5</b> Factor Level Information</a></li>
<li class="chapter" data-level="3.3.6" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#covariances-and-correlations"><i class="fa fa-check"></i><b>3.3.6</b> Covariances and Correlations</a></li>
<li class="chapter" data-level="3.3.7" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#applying-functions-to-multiple-variables"><i class="fa fa-check"></i><b>3.3.7</b> Applying Functions to Multiple Variables</a></li>
<li class="chapter" data-level="3.3.8" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#applying-functions-at-levels-of-factors"><i class="fa fa-check"></i><b>3.3.8</b> Applying Functions at Levels of Factors</a></li>
<li class="chapter" data-level="3.3.9" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#making-a-table"><i class="fa fa-check"></i><b>3.3.9</b> Making a Table</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#students-t-test-in-r"><i class="fa fa-check"></i><b>3.4</b> Student’s t-Test in R</a><ul>
<li class="chapter" data-level="3.4.1" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#one-sample-t-test"><i class="fa fa-check"></i><b>3.4.1</b> One Sample t-Test</a></li>
<li class="chapter" data-level="3.4.2" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#two-sample-t-test"><i class="fa fa-check"></i><b>3.4.2</b> Two Sample t-Test</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#one-way-anova-in-r"><i class="fa fa-check"></i><b>3.5</b> One-Way ANOVA in R</a><ul>
<li class="chapter" data-level="3.5.1" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#omnibus-f-test"><i class="fa fa-check"></i><b>3.5.1</b> Omnibus F-Test</a></li>
<li class="chapter" data-level="3.5.2" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#pairwise-comparisons-tukeys-hsd"><i class="fa fa-check"></i><b>3.5.2</b> Pairwise Comparisons (Tukey’s HSD)</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#correlation-tests-in-r"><i class="fa fa-check"></i><b>3.6</b> Correlation Tests in R</a></li>
<li class="chapter" data-level="3.7" data-path="simple-statistics-in-r.html"><a href="simple-statistics-in-r.html#exercises-2"><i class="fa fa-check"></i><b>3.7</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html"><i class="fa fa-check"></i><b>4</b> Linear Regression in R</a><ul>
<li class="chapter" data-level="4.1" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#chapter-outline-and-goals-1"><i class="fa fa-check"></i><b>4.1</b> Chapter Outline and Goals</a></li>
<li class="chapter" data-level="4.2" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#minnesota-beer-data-reminder"><i class="fa fa-check"></i><b>4.2</b> Minnesota Beer Data (Reminder)</a><ul>
<li class="chapter" data-level="4.2.1" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#overview-2"><i class="fa fa-check"></i><b>4.2.1</b> Overview</a></li>
<li class="chapter" data-level="4.2.2" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#load-and-look-at-the-data"><i class="fa fa-check"></i><b>4.2.2</b> Load and Look at the Data</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#simple-linear-regression"><i class="fa fa-check"></i><b>4.3</b> Simple Linear Regression</a><ul>
<li class="chapter" data-level="4.3.1" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#fit-the-model"><i class="fa fa-check"></i><b>4.3.1</b> Fit the Model</a></li>
<li class="chapter" data-level="4.3.2" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#inference-information"><i class="fa fa-check"></i><b>4.3.2</b> Inference Information</a></li>
<li class="chapter" data-level="4.3.3" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#plot-the-regression-line"><i class="fa fa-check"></i><b>4.3.3</b> Plot the Regression Line</a></li>
<li class="chapter" data-level="4.3.4" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#diagnostic-and-influence-plots"><i class="fa fa-check"></i><b>4.3.4</b> Diagnostic and Influence Plots</a></li>
<li class="chapter" data-level="4.3.5" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#prediction-for-new-data"><i class="fa fa-check"></i><b>4.3.5</b> Prediction for New Data</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#multiple-linear-regression"><i class="fa fa-check"></i><b>4.4</b> Multiple Linear Regression</a><ul>
<li class="chapter" data-level="4.4.1" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#overview-3"><i class="fa fa-check"></i><b>4.4.1</b> Overview</a></li>
<li class="chapter" data-level="4.4.2" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#additive-effects"><i class="fa fa-check"></i><b>4.4.2</b> Additive Effects</a></li>
<li class="chapter" data-level="4.4.3" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#interaction-effects"><i class="fa fa-check"></i><b>4.4.3</b> Interaction Effects</a></li>
<li class="chapter" data-level="4.4.4" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#comparing-fit-models"><i class="fa fa-check"></i><b>4.4.4</b> Comparing Fit Models</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="linear-regression-in-r.html"><a href="linear-regression-in-r.html#exercises-3"><i class="fa fa-check"></i><b>4.5</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html"><i class="fa fa-check"></i><b>5</b> Logistic Regression in R</a><ul>
<li class="chapter" data-level="5.1" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#introduction"><i class="fa fa-check"></i><b>5.1</b> Introduction</a><ul>
<li class="chapter" data-level="5.1.1" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#goals"><i class="fa fa-check"></i><b>5.1.1</b> Goals</a></li>
<li class="chapter" data-level="5.1.2" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#horseshoe-crab-data"><i class="fa fa-check"></i><b>5.1.2</b> Horseshoe Crab Data</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#model-basics"><i class="fa fa-check"></i><b>5.2</b> Model Basics</a><ul>
<li class="chapter" data-level="5.2.1" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#notation-and-setup"><i class="fa fa-check"></i><b>5.2.1</b> Notation and Setup</a></li>
<li class="chapter" data-level="5.2.2" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#fit-a-logistic-regression-model"><i class="fa fa-check"></i><b>5.2.2</b> Fit a Logistic Regression Model</a></li>
<li class="chapter" data-level="5.2.3" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#interpret-the-model"><i class="fa fa-check"></i><b>5.2.3</b> Interpret the Model</a></li>
<li class="chapter" data-level="5.2.4" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#calculate-probabilities"><i class="fa fa-check"></i><b>5.2.4</b> Calculate Probabilities</a></li>
<li class="chapter" data-level="5.2.5" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#test-a-regression-coefficient"><i class="fa fa-check"></i><b>5.2.5</b> Test a Regression Coefficient</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#half-time-exercises"><i class="fa fa-check"></i><b>5.3</b> Half-Time Exercises</a><ul>
<li class="chapter" data-level="5.3.1" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#female-horseshoe-crab-weight"><i class="fa fa-check"></i><b>5.3.1</b> Female Horseshoe Crab Weight</a></li>
<li class="chapter" data-level="5.3.2" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#boundary-water-blowdown"><i class="fa fa-check"></i><b>5.3.2</b> Boundary Water Blowdown</a></li>
<li class="chapter" data-level="5.3.3" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#beer"><i class="fa fa-check"></i><b>5.3.3</b> Beer</a></li>
<li class="chapter" data-level="5.3.4" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#state-colors"><i class="fa fa-check"></i><b>5.3.4</b> State Colors</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#beyond-the-basics"><i class="fa fa-check"></i><b>5.4</b> Beyond the Basics</a><ul>
<li class="chapter" data-level="5.4.1" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#interpret-the-model-again"><i class="fa fa-check"></i><b>5.4.1</b> Interpret the Model (Again!)</a></li>
<li class="chapter" data-level="5.4.2" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#incorporate-a-categorical-predictor"><i class="fa fa-check"></i><b>5.4.2</b> Incorporate a Categorical Predictor</a></li>
<li class="chapter" data-level="5.4.3" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#incorporate-multiple-predictors"><i class="fa fa-check"></i><b>5.4.3</b> Incorporate Multiple Predictors</a></li>
<li class="chapter" data-level="5.4.4" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#test-a-regression-coefficient-again"><i class="fa fa-check"></i><b>5.4.4</b> Test a Regression Coefficient (Again!)</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#more-exercises"><i class="fa fa-check"></i><b>5.5</b> More Exercises</a><ul>
<li class="chapter" data-level="5.5.1" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#crabs-revisited"><i class="fa fa-check"></i><b>5.5.1</b> Crabs, Revisited</a></li>
<li class="chapter" data-level="5.5.2" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#beer-revisited"><i class="fa fa-check"></i><b>5.5.2</b> Beer, Revisited</a></li>
<li class="chapter" data-level="5.5.3" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#state-colors-revisited"><i class="fa fa-check"></i><b>5.5.3</b> State Colors, Revisited</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#partial-solutions"><i class="fa fa-check"></i><b>5.6</b> Partial Solutions</a><ul>
<li class="chapter" data-level="5.6.1" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#crab-weight"><i class="fa fa-check"></i><b>5.6.1</b> Crab Weight</a></li>
<li class="chapter" data-level="5.6.2" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#boundary-water-blowdown-1"><i class="fa fa-check"></i><b>5.6.2</b> Boundary Water Blowdown</a></li>
<li class="chapter" data-level="5.6.3" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#beer-1"><i class="fa fa-check"></i><b>5.6.3</b> Beer</a></li>
<li class="chapter" data-level="5.6.4" data-path="logistic-regression-in-r.html"><a href="logistic-regression-in-r.html#state-colors-1"><i class="fa fa-check"></i><b>5.6.4</b> State Colors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html"><i class="fa fa-check"></i><b>6</b> Using R Reproducibly</a><ul>
<li class="chapter" data-level="6.1" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#types-of-reproducibility"><i class="fa fa-check"></i><b>6.1</b> Types of Reproducibility</a></li>
<li class="chapter" data-level="6.2" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#general-principles-of-reproducibility"><i class="fa fa-check"></i><b>6.2</b> General Principles of Reproducibility</a><ul>
<li class="chapter" data-level="6.2.1" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#dont-do-things-by-hand"><i class="fa fa-check"></i><b>6.2.1</b> Don’t do things by hand</a></li>
<li class="chapter" data-level="6.2.2" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#automate-where-you-can"><i class="fa fa-check"></i><b>6.2.2</b> Automate where you can</a></li>
<li class="chapter" data-level="6.2.3" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#use-version-control"><i class="fa fa-check"></i><b>6.2.3</b> Use Version Control</a></li>
<li class="chapter" data-level="6.2.4" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#document-your-environment"><i class="fa fa-check"></i><b>6.2.4</b> Document your environment</a></li>
<li class="chapter" data-level="6.2.5" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#document-your-analysis"><i class="fa fa-check"></i><b>6.2.5</b> Document your analysis</a></li>
<li class="chapter" data-level="6.2.6" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#make-your-data-open"><i class="fa fa-check"></i><b>6.2.6</b> Make your data open</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#starting-a-reproducible-workflow-in-r"><i class="fa fa-check"></i><b>6.3</b> Starting a Reproducible Workflow in R</a><ul>
<li class="chapter" data-level="6.3.1" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#organization"><i class="fa fa-check"></i><b>6.3.1</b> Organization</a></li>
<li class="chapter" data-level="6.3.2" data-path="using-r-reproducibly.html"><a href="using-r-reproducibly.html#anatomy-of-a-script"><i class="fa fa-check"></i><b>6.3.2</b> Anatomy of a script</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html"><i class="fa fa-check"></i><b>7</b> An R Markdown Demo</a><ul>
<li class="chapter" data-level="7.1" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#license"><i class="fa fa-check"></i><b>7.1</b> License</a></li>
<li class="chapter" data-level="7.2" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#r"><i class="fa fa-check"></i><b>7.2</b> R</a></li>
<li class="chapter" data-level="7.3" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#rendering"><i class="fa fa-check"></i><b>7.3</b> Rendering</a></li>
<li class="chapter" data-level="7.4" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#markdown"><i class="fa fa-check"></i><b>7.4</b> Markdown</a></li>
<li class="chapter" data-level="7.5" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#r-markdown"><i class="fa fa-check"></i><b>7.5</b> R Markdown</a><ul>
<li class="chapter" data-level="7.5.1" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#look"><i class="fa fa-check"></i><b>7.5.1</b> Look</a></li>
<li class="chapter" data-level="7.5.2" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#rdo"><i class="fa fa-check"></i><b>7.5.2</b> What Does It Do?</a></li>
<li class="chapter" data-level="7.5.3" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#why-do-we-want-it"><i class="fa fa-check"></i><b>7.5.3</b> Why Do We Want It?</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#examples-not-involving-r"><i class="fa fa-check"></i><b>7.6</b> Examples Not Involving R</a><ul>
<li class="chapter" data-level="7.6.1" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#title-author-date"><i class="fa fa-check"></i><b>7.6.1</b> Title, Author, Date</a></li>
<li class="chapter" data-level="7.6.2" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#headers"><i class="fa fa-check"></i><b>7.6.2</b> Headers</a></li>
<li class="chapter" data-level="7.6.3" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#paragraphs"><i class="fa fa-check"></i><b>7.6.3</b> Paragraphs</a></li>
<li class="chapter" data-level="7.6.4" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#fonts"><i class="fa fa-check"></i><b>7.6.4</b> Fonts</a></li>
<li class="chapter" data-level="7.6.5" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#lists"><i class="fa fa-check"></i><b>7.6.5</b> Lists</a></li>
<li class="chapter" data-level="7.6.6" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#html-links"><i class="fa fa-check"></i><b>7.6.6</b> HTML Links</a></li>
<li class="chapter" data-level="7.6.7" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#tables"><i class="fa fa-check"></i><b>7.6.7</b> Tables</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#examples-involving-r"><i class="fa fa-check"></i><b>7.7</b> Examples Involving R</a><ul>
<li class="chapter" data-level="7.7.1" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#code-chunks"><i class="fa fa-check"></i><b>7.7.1</b> Code Chunks</a></li>
<li class="chapter" data-level="7.7.2" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#code-chunks-with-options"><i class="fa fa-check"></i><b>7.7.2</b> Code Chunks With Options</a></li>
<li class="chapter" data-level="7.7.3" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#plots"><i class="fa fa-check"></i><b>7.7.3</b> Plots</a></li>
<li class="chapter" data-level="7.7.4" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#r-in-text"><i class="fa fa-check"></i><b>7.7.4</b> R in Text</a></li>
<li class="chapter" data-level="7.7.5" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#rtables"><i class="fa fa-check"></i><b>7.7.5</b> Tables</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#latex-math"><i class="fa fa-check"></i><b>7.8</b> LaTeX Math</a></li>
<li class="chapter" data-level="7.9" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#caching-computation"><i class="fa fa-check"></i><b>7.9</b> Caching Computation</a></li>
<li class="chapter" data-level="7.10" data-path="an-r-markdown-demo.html"><a href="an-r-markdown-demo.html#summary"><i class="fa fa-check"></i><b>7.10</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="git-version-control.html"><a href="git-version-control.html"><i class="fa fa-check"></i><b>8</b> Git (Version Control)</a><ul>
<li class="chapter" data-level="8.1" data-path="git-version-control.html"><a href="git-version-control.html#license-1"><i class="fa fa-check"></i><b>8.1</b> License</a></li>
<li class="chapter" data-level="8.2" data-path="git-version-control.html"><a href="git-version-control.html#r-1"><i class="fa fa-check"></i><b>8.2</b> R</a></li>
<li class="chapter" data-level="8.3" data-path="git-version-control.html"><a href="git-version-control.html#version-control"><i class="fa fa-check"></i><b>8.3</b> Version Control</a><ul>
<li class="chapter" data-level="8.3.1" data-path="git-version-control.html"><a href="git-version-control.html#what-is-it"><i class="fa fa-check"></i><b>8.3.1</b> What is It?</a></li>
<li class="chapter" data-level="8.3.2" data-path="git-version-control.html"><a href="git-version-control.html#very-old-fashioned-version-control"><i class="fa fa-check"></i><b>8.3.2</b> Very Old Fashioned Version Control</a></li>
<li class="chapter" data-level="8.3.3" data-path="git-version-control.html"><a href="git-version-control.html#a-plethora-of-version-control-systems"><i class="fa fa-check"></i><b>8.3.3</b> A Plethora of Version Control Systems</a></li>
<li class="chapter" data-level="8.3.4" data-path="git-version-control.html"><a href="git-version-control.html#why"><i class="fa fa-check"></i><b>8.3.4</b> Why?</a></li>
<li class="chapter" data-level="8.3.5" data-path="git-version-control.html"><a href="git-version-control.html#mindshare"><i class="fa fa-check"></i><b>8.3.5</b> Mindshare</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="git-version-control.html"><a href="git-version-control.html#git"><i class="fa fa-check"></i><b>8.4</b> Git</a><ul>
<li class="chapter" data-level="8.4.1" data-path="git-version-control.html"><a href="git-version-control.html#git-versus-github"><i class="fa fa-check"></i><b>8.4.1</b> Git versus GitHub</a></li>
<li class="chapter" data-level="8.4.2" data-path="git-version-control.html"><a href="git-version-control.html#git-and-github-and-rstudio"><i class="fa fa-check"></i><b>8.4.2</b> Git and GitHub and RStudio</a></li>
<li class="chapter" data-level="8.4.3" data-path="git-version-control.html"><a href="git-version-control.html#getting-git"><i class="fa fa-check"></i><b>8.4.3</b> Getting Git</a></li>
<li class="chapter" data-level="8.4.4" data-path="git-version-control.html"><a href="git-version-control.html#what"><i class="fa fa-check"></i><b>8.4.4</b> What?</a></li>
<li class="chapter" data-level="8.4.5" data-path="git-version-control.html"><a href="git-version-control.html#using-git"><i class="fa fa-check"></i><b>8.4.5</b> Using Git</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="git-version-control.html"><a href="git-version-control.html#tell-git-who-you-are"><i class="fa fa-check"></i><b>8.5</b> Tell Git Who You Are</a></li>
<li class="chapter" data-level="8.6" data-path="git-version-control.html"><a href="git-version-control.html#starting-a-new-project-locally"><i class="fa fa-check"></i><b>8.6</b> Starting a New Project Locally</a></li>
<li class="chapter" data-level="8.7" data-path="git-version-control.html"><a href="git-version-control.html#starting-an-r-project-that-will-be-a-cran-package"><i class="fa fa-check"></i><b>8.7</b> Starting an R Project that will be a CRAN Package</a></li>
<li class="chapter" data-level="8.8" data-path="git-version-control.html"><a href="git-version-control.html#cloning-an-existing-project"><i class="fa fa-check"></i><b>8.8</b> Cloning an Existing Project</a></li>
<li class="chapter" data-level="8.9" data-path="git-version-control.html"><a href="git-version-control.html#keys"><i class="fa fa-check"></i><b>8.9</b> GitHub and SSH keys</a></li>
<li class="chapter" data-level="8.10" data-path="git-version-control.html"><a href="git-version-control.html#halftime-summary"><i class="fa fa-check"></i><b>8.10</b> Halftime Summary</a></li>
<li class="chapter" data-level="8.11" data-path="git-version-control.html"><a href="git-version-control.html#everyday-git-one-computer-no-collaboration"><i class="fa fa-check"></i><b>8.11</b> Everyday Git: One Computer, No Collaboration</a><ul>
<li class="chapter" data-level="8.11.1" data-path="git-version-control.html"><a href="git-version-control.html#commits"><i class="fa fa-check"></i><b>8.11.1</b> Commits</a></li>
<li class="chapter" data-level="8.11.2" data-path="git-version-control.html"><a href="git-version-control.html#status"><i class="fa fa-check"></i><b>8.11.2</b> Status</a></li>
<li class="chapter" data-level="8.11.3" data-path="git-version-control.html"><a href="git-version-control.html#the-file-.gitignore"><i class="fa fa-check"></i><b>8.11.3</b> The File <code>.gitignore</code></a></li>
<li class="chapter" data-level="8.11.4" data-path="git-version-control.html"><a href="git-version-control.html#log"><i class="fa fa-check"></i><b>8.11.4</b> Log</a></li>
<li class="chapter" data-level="8.11.5" data-path="git-version-control.html"><a href="git-version-control.html#diff"><i class="fa fa-check"></i><b>8.11.5</b> Diff</a></li>
</ul></li>
<li class="chapter" data-level="8.12" data-path="git-version-control.html"><a href="git-version-control.html#everyday-git-github-or-multiple-computers"><i class="fa fa-check"></i><b>8.12</b> Everyday Git: GitHub or Multiple Computers</a></li>
<li class="chapter" data-level="8.13" data-path="git-version-control.html"><a href="git-version-control.html#everyday-git-collaboration"><i class="fa fa-check"></i><b>8.13</b> Everyday Git: Collaboration</a><ul>
<li class="chapter" data-level="8.13.1" data-path="git-version-control.html"><a href="git-version-control.html#setup"><i class="fa fa-check"></i><b>8.13.1</b> Setup</a></li>
<li class="chapter" data-level="8.13.2" data-path="git-version-control.html"><a href="git-version-control.html#workflow"><i class="fa fa-check"></i><b>8.13.2</b> Workflow</a></li>
</ul></li>
<li class="chapter" data-level="8.14" data-path="git-version-control.html"><a href="git-version-control.html#wrapup"><i class="fa fa-check"></i><b>8.14</b> Wrapup</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Data Analysis with R &amp; Reproducible Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="logistic-regression-in-r" class="section level1">
<h1><span class="header-section-number"> 5</span> Logistic Regression in R</h1>
<p><em>Author: Christina Knudson</em></p>
<div id="introduction" class="section level2">
<h2><span class="header-section-number">5.1</span> Introduction</h2>
<p>The previous chapter covered linear regression, which models a Gaussian response variable. This chapter covers logistic regression, which is used to model a binary response variable. Here are some examples of binary responses:</p>
<ul>
<li>Whether or not a person wears a helmet while biking</li>
<li>Whether or not a dog is adopted</li>
<li>Whether or not a beer is given an award</li>
<li>Whether or not a tree survives a storm</li>
</ul>
<div id="goals" class="section level3">
<h3><span class="header-section-number">5.1.1</span> Goals</h3>
<p>In this chapter, we will cover how to…</p>
<ul>
<li>Fit a logistic regression model in R with quantitative and/or categorical predictors.</li>
<li>Interpret logistic regression model.</li>
<li>Calculate probabilities.</li>
<li>Test the significance of regression coefficients.</li>
</ul>
<p>R’s <strong>glm</strong> (generalized linear model) function will be the primary tool used in the chapter.</p>
</div>
<div id="horseshoe-crab-data" class="section level3">
<h3><span class="header-section-number">5.1.2</span> Horseshoe Crab Data</h3>
<p>Throughout this module, we will refer to the horseshoe crab data. Some female crabs attract many males while others do not attract any. The males that cluster around a female are called “satellites.” In order to understand what influences the presence of satellite crabs, researchers selected female crabs and collected data on the following characteristics:</p>
<ul>
<li>the color of her shell</li>
<li>the condition of her spine</li>
<li>the width of her carapace shell (in centimeters)</li>
<li>the number of male satellites</li>
<li>the weight of the female (in grams)</li>
</ul>
<p>In today’s example, we will use the width of a female’s shell to predict the probability of her having one or more satellites. Let’s start by loading the data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">crabs &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;http://www.cknudson.com/data/crabs.csv&quot;</span>)
<span class="kw">head</span>(crabs)</code></pre></div>
<pre><code>##    color spine width satell weight y
## 1 medium   bad  28.3      8   3050 1
## 2   dark   bad  22.5      0   1550 0
## 3  light  good  26.0      9   2300 1
## 4   dark   bad  24.8      0   2100 0
## 5   dark   bad  26.0      4   2600 1
## 6 medium   bad  23.8      0   2100 0</code></pre>
<p>You can learn more about this data set <a href="http://users.stat.ufl.edu/~aa/cda/data.html">here</a>.</p>
</div>
</div>
<div id="model-basics" class="section level2">
<h2><span class="header-section-number">5.2</span> Model Basics</h2>
<div id="notation-and-setup" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Notation and Setup</h3>
<p>Recall that a simple linear regression model has the following form: <span class="math display">\[
\hat{y}_i = \beta_0 + \beta_1 x_i 
\]</span> where <span class="math inline">\(x_i\)</span> is the predictor, <span class="math inline">\(\beta_0\)</span> is the unknown regression intercept, <span class="math inline">\(\beta_1\)</span> is the unknown regression slope, and <span class="math inline">\(\hat{y}_i\)</span> is the predicted response given <span class="math inline">\(x_i\)</span>.</p>
<p>In order to model a binary response variable, we need to introduce <span class="math inline">\(p_i\)</span>, the probability of something happening. For example, this might be the probability of a person wearing a helmet, the probability of a dog being adopted, or the probability of a beer winning an award. Then our logistic regression model has the following form: <span class="math display">\[
\log \left( \dfrac{p_i}{1-p_i} \right) = \beta_0 + \beta_1 x_i .
\]</span></p>
<p>Recall that we estimated <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> to characterize the linear relationship between <span class="math inline">\(x_i\)</span> and <span class="math inline">\(y_i\)</span> in the simple linear regression setting. In the logistic regression setting, we will estimate <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> in order to understand the relationship between <span class="math inline">\(x_i\)</span> and <span class="math inline">\(p_i\)</span>.</p>
<p>As a final introductory note, we define the odds as <span class="math inline">\(\dfrac{p_i}{1-p_i}\)</span>.</p>
</div>
<div id="fit-a-logistic-regression-model" class="section level3">
<h3><span class="header-section-number">5.2.2</span> Fit a Logistic Regression Model</h3>
<p>To fit a logistic regression model, we can use the <strong>glm</strong> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod &lt;-<span class="st"> </span><span class="kw">glm</span>(y <span class="op">~</span><span class="st"> </span>width, <span class="dt">family =</span> binomial, <span class="dt">data =</span> crabs)</code></pre></div>
<p>The first input is the regression formula (Response ~ Predictor), the second input indicates we have a binary response, and the third input is the data frame. To find the regression coefficients (i.e. the estimates of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>), we can use the <strong>coef</strong> command</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">coef</span>(mod)</code></pre></div>
<pre><code>## (Intercept)       width 
## -12.3508177   0.4972306</code></pre>
<p>We can now enter these estimates into our logistic regression equation, just as we did in the simple linear regression setting. Our logistic regression equation is <span class="math display">\[
\log \left( \dfrac{p_i}{1-p_i} \right) = 12.3508 + 0.4972 \; \text{width}_i, 
\]</span> where <span class="math inline">\(\text{width}_i\)</span> is the width of a female crab’s carapace shell and <span class="math inline">\(p_i\)</span> is her probability of having one or more satellites.</p>
</div>
<div id="interpret-the-model" class="section level3">
<h3><span class="header-section-number">5.2.3</span> Interpret the Model</h3>
<p>To do some basic interpretation, let’s focus on the predictor’s coefficient: 0.4972. First, notice this is a <strong>positive</strong> number. This tells us that wider crabs have <strong>higher</strong> chances of having one or more satellites. If the predictor’s coefficient were <strong>zero</strong>, there would be <strong>no</strong> linear relationship between the width of a female’s shell and her log odds of having one or more satellites. If the predictor’s coefficient were <strong>negative</strong>, then wider crabs would have <strong>lower</strong> chances of having one or more satellites.</p>
</div>
<div id="calculate-probabilities" class="section level3">
<h3><span class="header-section-number">5.2.4</span> Calculate Probabilities</h3>
Let’s use our model for a female crab with a carapace shell that is 25 centimeters in width. (Note: this crab’s shell width is within the range of our data set.) We start by simply substituting this crab’s width into our regression equation:
<span class="math display">\[\begin{align*}
\log \left( \dfrac{p_i}{1-p_i} \right) &amp;= -12.3508 + 0.4972 \; \text{width}_i \\
 &amp;= -12.3508 + 0.4972 * 25 \\
 &amp;= 0.0792.
\end{align*}\]</span>
<p>We could say that the log odds of a 25 cm female having satellites is about 0.0792, but let’s make this more interpretable to everyday humans by translating this to a probability. We use a little algebra to solve for <span class="math inline">\(p_i\)</span>:</p>
<span class="math display">\[\begin{align*}
\log \left( \dfrac{p_i}{1-p_i} \right) &amp;= 0.0792 \\
\Rightarrow \left( \dfrac{p_i}{1-p_i} \right) &amp;= \exp(0.0792) \\
\Rightarrow p_i &amp;= \dfrac{\exp(0.0792)}{1+\exp(0.0792)} \\
&amp;= 0.5198
\end{align*}\]</span>
<p>Here is our interpretation: the probability of a 25 cm wide female crab having one of more satellites is about 0.5198.</p>
</div>
<div id="test-a-regression-coefficient" class="section level3">
<h3><span class="header-section-number">5.2.5</span> Test a Regression Coefficient</h3>
<p>An essential question in regression is “Does this predictor actually help us predict the response?” In other words, we want to know whether there really is a relationship between our predictor and our response.</p>
<p>In the context of the crabs, we want to know whether the carapace width really does have a linear relationship with the log odds of satellites.</p>
<ul>
<li>The null hypothesis is that her carapace width has no linear relationship to her log odds of having satellites.</li>
<li>The alternative hypothesis is that her carapace width has a linear relationship to her log odds of having satellites.</li>
</ul>
<p>Remember: we assume there is <em>no</em> relationship until we find evidence that there <em>is</em> a relationship. That is, we assume that carapace width is unrelated to the probability of satellites; in order to say the carapace width is related to the probability of satellites, we need evidence. This evidence comes in the form of a statistical test.</p>
<p>The results of this test are reported in the <strong>summary</strong> command, which was introduced in the linear regression setting. Below is the summary for our crab model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(mod)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ width, family = binomial, data = crabs)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.0281  -1.0458   0.5480   0.9066   1.6942  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -12.3508     2.6287  -4.698 2.62e-06 ***
## width         0.4972     0.1017   4.887 1.02e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 225.76  on 172  degrees of freedom
## Residual deviance: 194.45  on 171  degrees of freedom
## AIC: 198.45
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Although the summary provides many details about our model, we focus for now on the coefficients table in the center of the summary output. Recall that our model has two regression coefficients: the intercept <span class="math inline">\(\beta_0\)</span> and the slope <span class="math inline">\(\beta_1\)</span>. The first row of the coefficients table displays information for <span class="math inline">\(\beta_0\)</span> and the second row displays information for <span class="math inline">\(\beta_1\)</span>. The columns of the coefficients table provide the estimates of our regression coefficients, their standard errors (smaller standard errors indicate higher certainty), test statistics (for testing whether the regression coefficients differ from zero), and the p-values associated with the test statistics.</p>
<p>In order to answer our question (“Does this predictor actually help us predict the response?”), we focus on <span class="math inline">\(\beta_1\)</span>, the regression coefficient on the predictor. (Recall that if <span class="math inline">\(\beta_1 = 0\)</span>, then the log odds have no linear relationship with the predictor.) We find the test results in te two right-most columns and the second row in the the coefficients table of the summary. These entries show us that our test statistic is 4.887 and our p-value is 1.02e-06 (or <span class="math inline">\(1.02 \times 10^{-6}\)</span>). We compare our p-value to a “significance level” (such as <span class="math inline">\(0.05\)</span>); <strong>because our p-value is smaller than our significance level, we have evidence that the log odds of satellites have a significant linear relationship with the carapace width.</strong></p>
</div>
</div>
<div id="half-time-exercises" class="section level2">
<h2><span class="header-section-number">5.3</span> Half-Time Exercises</h2>
<div id="female-horseshoe-crab-weight" class="section level3">
<h3><span class="header-section-number">5.3.1</span> Female Horseshoe Crab Weight</h3>
<p>Continue using the horseshoe crab data to investigate the relationship between a female’s weight and the log odds of her having satellites.</p>
<ul>
<li>Create a logistic regression using the female’s weight as the predictor and whether she has satellites as the response variable.</li>
<li>Write down the regression equation.</li>
<li>Do heavier females having higher or lower chances of having satellites?</li>
<li>Consider a female weighing 2000 grams. What is the probability that she has one or more satellites?</li>
<li>Is there a linear relationship between a female crab’s weight and her log odds of satellites? Find the p-value and use a significance level of <span class="math inline">\(0.05\)</span>.</li>
</ul>
</div>
<div id="boundary-water-blowdown" class="section level3">
<h3><span class="header-section-number">5.3.2</span> Boundary Water Blowdown</h3>
<p>The Boundary Water Canoe Area experienced wind speeds over 90 miles per hour on July 4, 1999. As a result, many trees were blown down. The data set below contains information on the diameter of each tree (<strong>D</strong>) and whether the tree died (<strong>y</strong>). <strong>y</strong> is 1 if the tree died and 0 if the tree survived. You can learn more about this data set <a href="https://www.rdocumentation.org/packages/alr4/versions/1.0.5/topics/Blowdown">here</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">blowdown &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;http://www.cknudson.com/data/blowdown.csv&quot;</span>)</code></pre></div>
<p>Use this data set to understand the relationship between a tree’s diameter and its log odds of death.</p>
<ul>
<li>Create a logistic regression using the tree’s diameter the predictor and whether it died as the response variable.</li>
<li>Write down the regression equation.</li>
<li>Did thicker trees having higher or lower chances of dying?</li>
<li>Consider a tree 20 cm in diameter. What is the probability that it died?</li>
<li>Is there a linear relationship between the tree’s diameter and its log odds of dying? Find the p-value and use a significance level of <span class="math inline">\(0.05\)</span>.</li>
</ul>
</div>
<div id="beer" class="section level3">
<h3><span class="header-section-number">5.3.3</span> Beer</h3>
<p>Recall the beer data set introduced by Alicia Johnson and Nathaniel Helwig. Imagine that you have a friend with a rather black-and-white outlook. If a beer’s rating is 90 or higher, your friend considers this beer good. Scores lower than 90 indicate the beer is not good, according to your friend’s rule. We have added a binary variable (<strong>Good</strong>) to to represent your friend’s classification strategy: <strong>Good</strong> is 1 if the beer has a score of at least 90 and 0 otherwise.</p>
<ul>
<li>Use logistic regression to decide whether beers with higher <strong>ABV</strong> (alcohol by volume) are more likely to be “Good.”</li>
<li>Choose your favorite beer off the list and calculate its probability of having a score of at least 90.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">beer &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;http://www.cknudson.com/data/MNbeer.csv&quot;</span>)</code></pre></div>
</div>
<div id="state-colors" class="section level3">
<h3><span class="header-section-number">5.3.4</span> State Colors</h3>
<p>Recall the election data set introduced by Alicia Johnson. The variable <strong>Red</strong> has been added to the data set to indicate whether the state’s color is red (1 if red, 0 otherwise).</p>
<ul>
<li>Is per capita income related to whether a state is red?</li>
<li>If a state has a high per capita income, is it more or less likely to be red?</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">election &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;https://www.macalester.edu/~ajohns24/data/IMAdata1.csv&quot;</span>)
election<span class="op">$</span>Red &lt;-<span class="st"> </span><span class="kw">as.numeric</span>(election<span class="op">$</span>StateColor <span class="op">==</span><span class="st"> &quot;red&quot;</span>)</code></pre></div>
</div>
</div>
<div id="beyond-the-basics" class="section level2">
<h2><span class="header-section-number">5.4</span> Beyond the Basics</h2>
<div id="interpret-the-model-again" class="section level3">
<h3><span class="header-section-number">5.4.1</span> Interpret the Model (Again!)</h3>
<p>We can look beyond just whether the predictor’s coefficient (<span class="math inline">\(\beta_1\)</span>) is positive or negative. Exponentiating both sides of the regression equation produces <span class="math display">\[
\dfrac{p_i}{1-p_i} = \exp\left( \beta_0 + \beta_1 x_i \right) = \exp\left( \beta_0 \right) \exp\left(  \beta_1 x_i \right). 
\]</span></p>
<p>To understand the relationship between our predictor and the log odds, let’s see what happens when we increase <span class="math inline">\(x_i\)</span> by one unit. That is, let’s replace <span class="math inline">\(x_i\)</span> with <span class="math inline">\(x_i+1\)</span>.</p>
<p><span class="math display">\[
\dfrac{p_i}{1-p_i} =  \exp\left( \beta_0 \right) \exp\left(  \beta_1 (x_i+1) \right) = \exp\left( \beta_0 \right) \exp\left(  \beta_1 x_i \right)\exp\left(  \beta_1  \right). 
\]</span></p>
<p>That is, our odds for predictor value <span class="math inline">\(x_i\)</span> are <span class="math inline">\(\exp\left( \beta_0 \right) \exp\left( \beta_1 x_i \right)\)</span> while the odds for predictor value <span class="math inline">\(x_i+1\)</span> are <span class="math inline">\(\exp\left( \beta_0 \right) \exp\left( \beta_1 x_i \right)\exp\left( \beta_1 \right)\)</span>. These two odds differ by a factor of <span class="math inline">\(\exp(\beta_1)\)</span>. That is, the ratio of the two odds is <span class="math inline">\(\exp(\beta_1)\)</span>: <span class="math display">\[
\dfrac{\exp\left( \beta_0 \right) \exp\left(  \beta_1 x_i \right)\exp\left(  \beta_1  \right)}{\exp\left( \beta_0 \right) \exp\left(  \beta_1 x_i \right)} = \exp(\beta_1).
\]</span></p>
<p>Therefore, we can say that a one unit increase in the predictor is associated with a <span class="math inline">\(\exp(\beta_1)\)</span> multiplicative change in the odds. Let’s try this with the horseshoe crab carapace width model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">exp</span>(<span class="kw">coef</span>(mod))</code></pre></div>
<pre><code>##  (Intercept)        width 
## 4.326214e-06 1.644162e+00</code></pre>
<p>A one centimeter increase in carapace width is associated with a 1.64 multiplicative change in the odds of having satellites. Alternatively, imagine two female crabs that have carapace widths that differ by exactly 1 cm. The odds of the larger crab having satellites is approximately 1.64 times the odds of the smaller crab having satellites.</p>
</div>
<div id="incorporate-a-categorical-predictor" class="section level3">
<h3><span class="header-section-number">5.4.2</span> Incorporate a Categorical Predictor</h3>
<p>Rather than using a quantitative predictor, we can use a categorical predictor. Let’s try using the spine condition in our horseshoe crab data. Crabs were categorized according to whether they had two good spines (<em>good</em>), two worn or broken spines (<em>bad</em>), or one worn/broken spine and one good spine (<em>middle</em>).</p>
<p>We will fit the model using the following <strong>glm</strong> setup.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">spinemod &lt;-<span class="st"> </span><span class="kw">glm</span>(y <span class="op">~</span><span class="st"> </span><span class="dv">0</span> <span class="op">+</span><span class="st"> </span>spine, <span class="dt">data =</span> crabs, <span class="dt">family =</span> binomial)
<span class="kw">coef</span>(spinemod)</code></pre></div>
<pre><code>##    spinebad   spinegood spinemiddle 
##   0.5955087   0.8602013  -0.1335314</code></pre>
<p>This produces three log odds, one for each group (bad, good, and middle). If we eliminate the <strong>0+</strong>, we create a model with a reference group; this will compare the bad spine group to the other two groups.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">spinemod2 &lt;-<span class="st"> </span><span class="kw">glm</span>(y <span class="op">~</span><span class="st"> </span>spine, <span class="dt">data =</span> crabs, <span class="dt">family =</span> binomial)
<span class="kw">coef</span>(spinemod2)</code></pre></div>
<pre><code>## (Intercept)   spinegood spinemiddle 
##   0.5955087   0.2646926  -0.7290401</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">exp</span>(<span class="kw">coef</span>(spinemod2))</code></pre></div>
<pre><code>## (Intercept)   spinegood spinemiddle 
##   1.8139535   1.3030303   0.4823718</code></pre>
<p>This model tells us that</p>
<ul>
<li>the odds of satellites for a female with two bad spines is 1.8.</li>
<li>the odds of satellites for a female with two good spines is 1.3 times the odds of satellites for a female with two bad spines.</li>
<li>the odds of satellites for a female with one good spine and one bad spine is .48 times the odds of satellites for a female with two bad spines.</li>
</ul>
<p>Sometimes people have a hard time interpreting odds ratios below 1. In this case, it is useful to flip the ratio.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">1</span><span class="op">/</span><span class="kw">exp</span>(<span class="kw">coef</span>(spinemod2))</code></pre></div>
<pre><code>## (Intercept)   spinegood spinemiddle 
##   0.5512821   0.7674419   2.0730897</code></pre>
<p>Therefore, we can reword the third bullet to the following: the odds of satellites for a female with two bad spines is 2 times the odds of satellites for a female with one bad spine and one good spine.</p>
</div>
<div id="incorporate-multiple-predictors" class="section level3">
<h3><span class="header-section-number">5.4.3</span> Incorporate Multiple Predictors</h3>
<p>In the linear regression setting, you created models with multiple predictors. This is useful in the logistic regression setting as well. Let’s create a model with both the female’s carapace width and her weight. We expand our <strong>glm</strong> formula in the same way as you would expand the <strong>lm</strong> formula.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">multimod &lt;-<span class="st"> </span><span class="kw">glm</span>(y <span class="op">~</span><span class="st"> </span>weight <span class="op">+</span><span class="st"> </span>width, <span class="dt">data =</span> crabs, <span class="dt">family =</span> binomial)
<span class="kw">coef</span>(multimod)</code></pre></div>
<pre><code>##   (Intercept)        weight         width 
## -9.3547261192  0.0008337917  0.3067892044</code></pre>
<p>This produces the following logistic regression equation:</p>
<p><span class="math display">\[
\log \left( \dfrac{p_i}{1-p_i} \right) = -9.35 + 0.0008337917 \; \text{weight}_i + 0.3067892044 \; \text{width}_i .
\]</span></p>
<p>Equivalently, our model could be written as</p>
<p><span class="math display">\[
\ \dfrac{p_i}{1-p_i}  = \exp(-9.35) \; \exp \left( 0.0008337917 \; \text{weight}_i \right) \; \exp \left( 0.3067892044 \; \text{width}_i \right) .
\]</span></p>
<p>The exponentiated regression coefficients</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">round</span>(<span class="kw">exp</span>(<span class="kw">coef</span>(multimod)),<span class="dv">3</span>)</code></pre></div>
<pre><code>## (Intercept)      weight       width 
##       0.000       1.001       1.359</code></pre>
<p>tell us the following:</p>
<ul>
<li>Holding weight constant, a one centimeter increase in carapace width is associated with a 1.359 multiplicative change in the odds of having satellites.</li>
<li>Holding carapace width constant, a one gram increase in weight is associated with a 1.001 multiplicative change in the odds of having satellites.</li>
</ul>
<p>Of course, a one gram increase in weight is practically imperceptible. Let’s instead consider a 100 gram increase in weight.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">beta1 &lt;-<span class="st"> </span><span class="kw">coef</span>(multimod)[<span class="dv">2</span>]
<span class="kw">exp</span>(beta1 <span class="op">*</span><span class="st"> </span><span class="dv">100</span>)</code></pre></div>
<pre><code>##   weight 
## 1.086954</code></pre>
<p>Holding carapace width constant, a 100 gram increase in weight is associated with a 1.087 multiplicative change in the odds of having satellites.</p>
</div>
<div id="test-a-regression-coefficient-again" class="section level3">
<h3><span class="header-section-number">5.4.4</span> Test a Regression Coefficient (Again!)</h3>
<p>We discussed how to test a regression coefficient for a logistic model with a single predictor. You learned how to test a regression coefficient in multiple linear regression. Now it is time to test a logistic regression coefficient in models with multiple predictors.</p>
<p>Let’s test whether a logistic regression model with both carapace width and weight is better than a model with carapace width only. That is, we want to know whether the female’s weight contributes to the model. Again, we check the summary and look at the row labeled <strong>weight</strong>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(multimod)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ weight + width, family = binomial, data = crabs)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.1127  -1.0344   0.5304   0.9006   1.7207  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept) -9.3547261  3.5280465  -2.652  0.00801 **
## weight       0.0008338  0.0006716   1.241  0.21445   
## width        0.3067892  0.1819473   1.686  0.09177 . 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 225.76  on 172  degrees of freedom
## Residual deviance: 192.89  on 170  degrees of freedom
## AIC: 198.89
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>The p-value is reported as 0.21445. This is larger than any standard significance level. Therefore, we should remove the female’s weight from the model as it does not contribute a significant amount of information, after accounting for the female’s carapace width. We can state our conclusion more formally: after accounting for the female’s carapace width, we find no significant linear relationship between the female’s weight and her log odds of having satellites.</p>
</div>
</div>
<div id="more-exercises" class="section level2">
<h2><span class="header-section-number">5.5</span> More Exercises</h2>
<div id="crabs-revisited" class="section level3">
<h3><span class="header-section-number">5.5.1</span> Crabs, Revisited</h3>
<p>Use the output below to determine whether, after accounting for the female’s weight, there is a linear relationship between carapace width and the log odds of satellites.</p>
</div>
<div id="beer-revisited" class="section level3">
<h3><span class="header-section-number">5.5.2</span> Beer, Revisited</h3>
<p>Create a logistic regression for the log odds of a beer being “Good” using both ABV and IBU as predictors.</p>
<ul>
<li>Holding IBU constant, are beers with higher ABVs <strong>more</strong> or <strong>less</strong> likely to be “Good”?</li>
<li>After accounting for a beer’s IBU, is there a relationship between ABV and a beer’s log odds of being “Good”? Compare your p-value to a significance level of .1.</li>
</ul>
</div>
<div id="state-colors-revisited" class="section level3">
<h3><span class="header-section-number">5.5.3</span> State Colors, Revisited</h3>
<p>Use <strong>IncomeBracket</strong> to model the log odds of a state being red.</p>
<ul>
<li>Find the odds of a high income state being red.</li>
<li>Fill in the blank: the odds of a high income state being red are ____ times the odds of a low income state being red.</li>
</ul>
</div>
</div>
<div id="partial-solutions" class="section level2">
<h2><span class="header-section-number">5.6</span> Partial Solutions</h2>
<div id="crab-weight" class="section level3">
<h3><span class="header-section-number">5.6.1</span> Crab Weight</h3>
<p>We create the model and look at the summary to find the p-value for the coefficient on weight The p-value is small (<span class="math inline">\(1.45 \times 10^{-6}\)</span>) so we can conclude that a female crab’s weight <strong>does</strong> have a significant linear relationship with the log odds of her having one or more satellites.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">weightmod &lt;-<span class="st"> </span><span class="kw">glm</span>(y <span class="op">~</span><span class="st"> </span>weight, <span class="dt">family =</span> binomial, <span class="dt">data =</span> crabs)
<span class="kw">summary</span>(weightmod)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ weight, family = binomial, data = crabs)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.1108  -1.0749   0.5426   0.9122   1.6285  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -3.6947264  0.8801975  -4.198 2.70e-05 ***
## weight       0.0018151  0.0003767   4.819 1.45e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 225.76  on 172  degrees of freedom
## Residual deviance: 195.74  on 171  degrees of freedom
## AIC: 199.74
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>Now we can use our regression equation to calculate the probability of a 2000 gram female having one or more satellites.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">logodds &lt;-<span class="st"> </span><span class="kw">sum</span>(<span class="kw">coef</span>(weightmod) <span class="op">*</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2000</span>))
<span class="kw">exp</span>(logodds)<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="kw">exp</span>(logodds))</code></pre></div>
<pre><code>## [1] 0.4838963</code></pre>
<p>The probability of a 2000 gram female having satellites is about half (.48).</p>
</div>
<div id="boundary-water-blowdown-1" class="section level3">
<h3><span class="header-section-number">5.6.2</span> Boundary Water Blowdown</h3>
<p>We create the model, isolate the coefficients, and find the summary using the code below.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">treemod &lt;-<span class="st"> </span><span class="kw">glm</span>(y <span class="op">~</span><span class="st"> </span>D, <span class="dt">data =</span> blowdown, <span class="dt">family =</span> binomial)
<span class="kw">coef</span>(treemod)</code></pre></div>
<pre><code>## (Intercept)           D 
## -1.70211206  0.09755846</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(treemod)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = y ~ D, family = binomial, data = blowdown)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.6309  -0.9616  -0.7211   1.1495   1.7172  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -1.702112   0.082798  -20.56   &lt;2e-16 ***
## D            0.097558   0.004846   20.13   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 5057.9  on 3665  degrees of freedom
## Residual deviance: 4555.6  on 3664  degrees of freedom
## AIC: 4559.6
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>First, the coefficient on the diameter is positive. This tells us that larger trees were more likely to die. Moreover, the relationship between a trees diameter and its log odds of death is statistically significant: the p-value is quite small (smaller than <span class="math inline">\(2 \times 10^{-16}\)</span>).</p>
<p>Finally, the probability of death for a tree that was 20 cm in diameter is calculated below.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">(logodds &lt;-<span class="st"> </span><span class="kw">coef</span>(treemod) <span class="op">%*%</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">20</span>))</code></pre></div>
<pre><code>##           [,1]
## [1,] 0.2490571</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">exp</span>(logodds)<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="kw">exp</span>(logodds))</code></pre></div>
<pre><code>##           [,1]
## [1,] 0.5619444</code></pre>
</div>
<div id="beer-1" class="section level3">
<h3><span class="header-section-number">5.6.3</span> Beer</h3>
<p>We create the model and look at the summary to find the p-value for the coefficient on ABV. The p-value is small (<span class="math inline">\(0.00747\)</span>) so we can conclude that ABV <strong>does</strong> have a significant linear relationship with the log odds of a beer earning a score of at least 90.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">beermod &lt;-<span class="st"> </span><span class="kw">glm</span>(Good <span class="op">~</span><span class="st"> </span>ABV, <span class="dt">family =</span> binomial, <span class="dt">data =</span> beer)
<span class="kw">summary</span>(beermod)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Good ~ ABV, family = binomial, data = beer)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.3847  -0.8206  -0.4663   0.7230   2.1320  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)   
## (Intercept)  -9.7881     3.3959  -2.882  0.00395 **
## ABV           1.4662     0.5481   2.675  0.00747 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 51.564  on 43  degrees of freedom
## Residual deviance: 42.108  on 42  degrees of freedom
## AIC: 46.108
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Next, we create our model with both ABV and IBU.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">beermod2 &lt;-<span class="st"> </span><span class="kw">glm</span>(Good <span class="op">~</span><span class="st"> </span>ABV <span class="op">+</span><span class="st"> </span>IBU, <span class="dt">family =</span> binomial, <span class="dt">data =</span> beer)
<span class="kw">coef</span>(beermod2)</code></pre></div>
<pre><code>##  (Intercept)          ABV          IBU 
## -9.307699299  1.308989140  0.008248125</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(beermod2)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Good ~ ABV + IBU, family = binomial, data = beer)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.2930  -0.7759  -0.4435   0.7678   2.1315  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept) -9.307699   3.678245  -2.530   0.0114 *
## ABV          1.308989   0.721717   1.814   0.0697 .
## IBU          0.008248   0.025139   0.328   0.7428  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 51.564  on 43  degrees of freedom
## Residual deviance: 42.000  on 41  degrees of freedom
## AIC: 48
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>The coefficient on ABV is positive: this tells us that, after accounting for IBU, beers with higher ABV are more likely to be “Good.” The p-value for this regression coefficient is <span class="math inline">\(.0697 &lt; .1\)</span>, therefore we can conclude that, even after accounting for IBU, there is a significant linear relationship between a beers ABV and its log odds of being “Good.”</p>
</div>
<div id="state-colors-1" class="section level3">
<h3><span class="header-section-number">5.6.4</span> State Colors</h3>
<p>We create the model and look at the summary to find the p-value for the coefficient on per capita income. The p-value is very small (smaller than <span class="math inline">\(2.2 \times 10^{-16}\)</span>) so we can conclude that per capita income <strong>does</strong> have a significant linear relationship with the log odds of a state being red.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">electionmod &lt;-<span class="st"> </span><span class="kw">glm</span>(Red <span class="op">~</span><span class="st">  </span>per_capita_income, <span class="dt">family =</span> binomial, <span class="dt">data =</span> election)
<span class="kw">summary</span>(electionmod)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Red ~ per_capita_income, family = binomial, data = election)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -1.617  -1.146  -0.753   1.157   2.073  
## 
## Coefficients:
##                     Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)        1.649e+00  1.722e-01   9.575   &lt;2e-16 ***
## per_capita_income -7.339e-05  7.214e-06 -10.173   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 4352.6  on 3142  degrees of freedom
## Residual deviance: 4237.1  on 3141  degrees of freedom
## AIC: 4241.1
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lowhighmod &lt;-<span class="st"> </span><span class="kw">glm</span>(Red <span class="op">~</span><span class="st"> </span>IncomeBracket, <span class="dt">data =</span> election, <span class="dt">family =</span> binomial)
<span class="kw">exp</span>(<span class="kw">coef</span>(lowhighmod))</code></pre></div>
<pre><code>##      (Intercept) IncomeBracketlow 
##        0.6197836        1.8217084</code></pre>
<p>The odds of a high income state being red is about .62. The odds of a low income state being red are about 1.82 times the odds of a high income state being red. That is, low income states are more likely to be red than high income states.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="linear-regression-in-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="using-r-reproducibly.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"download": null,
"toc": {
"collapse": "section",
"depth": 2,
"scroll_highlight": true
},
"toolbar": {
"position": "fixed"
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
